<?xml version="1.0" encoding="utf-8"?><Database Name="SysFlexSeguros" Class="BDConexionCumplimientoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.25.24.3;Initial Catalog=SysFlexSeguros;Integrated Security=False;User ID=sa" SettingsObjectName="UtilidadesAmigos.Data.Properties.Settings" SettingsPropertyName="SysFlexSegurosConnectionString2" Provider="System.Data.SqlClient" />
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_MATRIZ_RIESGO" Method="SP_PROCESAR_INFORMACION_MATRIZ_RIESGO">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(31,0)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdTipoIdentificacion" Parameter="idTipoIdentificacion" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="IdTipoTercero" Parameter="idTipoTercero" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdNivel_Riesgo_TipoTercero" Parameter="idNivel_Riesgo_TipoTercero" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdArea" Parameter="idArea" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdNivel_Riesgo_Area" Parameter="idNivel_Riesgo_Area" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdPosicion" Parameter="idPosicion" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdNivel_Riesgo_Posicion" Parameter="idNivel_Riesgo_Posicion" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdNivelAcademico" Parameter="idNivelAcademico" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdNivel_Riesgo_NivelAcademico" Parameter="idNivel_Riesgo_NivelAcademico" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdPaisProcedencia" Parameter="idPaisProcedencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdNivel_Riesgo_PaisProcedencia" Parameter="idNivel_Riesgo_PaisProcedencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdPaisResidencia" Parameter="idPaisResidencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdNivel_Riesgo_PaisResidencia" Parameter="idNivel_Riesgo_PaisResidencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdProvincia" Parameter="idProvincia" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdNivel_Riesgo_Provincia" Parameter="idNivel_Riesgo_Provincia" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdSalarioDevengado" Parameter="idSalarioDevengado" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdNivel_Riesgo_SalarioDevengado" Parameter="idNivel_Riesgo_SalarioDevengado" Type="System.Int32" DbType="Int" />
    <Parameter Name="ActividadSegundaria" Parameter="actividadSegundaria" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="IdNivel_Riesgo_ActividadSegundaria" Parameter="idNivel_Riesgo_ActividadSegundaria" Type="System.Int32" DbType="Int" />
    <Parameter Name="IngresosAdicionales" Parameter="ingresosAdicionales" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdNivel_Riesgo_IngresosAdicionales" Parameter="idNivel_Riesgo_IngresosAdicionales" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdPEP" Parameter="idPEP" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdNivel_Riesgo_PEP" Parameter="idNivel_Riesgo_PEP" Type="System.Int32" DbType="Int" />
    <Parameter Name="PrimaAnual" Parameter="primaAnual" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdNivel_Riesgo_PrimaAnual" Parameter="idNivel_Riesgo_PrimaAnual" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdTipoMonitoreo" Parameter="idTipoMonitoreo" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdTipoDebidaDiligencia" Parameter="idTipoDebidaDiligencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdNivel_Riesgo_Consolidado" Parameter="idNivel_Riesgo_Consolidado" Type="System.Int32" DbType="Int" />
    <Parameter Name="Observaciones" Parameter="observaciones" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_MATRIZ_RIESGOResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(31,0)" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IdTipoTercero" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_TipoTercero" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdArea" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_Area" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdPosicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_Posicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdNivelAcademico" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_NivelAcademico" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdPaisProcedencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_PaisProcedencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdPaisResidencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_PaisResidencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdProvincia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_Provincia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSalarioDevengado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_SalarioDevengado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActividadSegundaria" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_ActividadSegundaria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IngresosAdicionales" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_IngresosAdicionales" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdPEP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_PEP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrimaAnual" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_PrimaAnual" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdTipoMonitoreo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdTipoDebidaDiligencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_Consolidado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Observaciones" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_MATRIZ_RIESGO" Method="SP_BUSCA_MATRIZ_RIESGO">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(31,0)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IdUsuarui" Parameter="idUsuarui" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdTipoIdentificacion" Parameter="idTipoIdentificacion" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="IdArea" Parameter="idArea" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdPosicion" Parameter="idPosicion" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_MATRIZ_RIESGOResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(31,0) NOT NULL" CanBeNull="false" />
      <Column Name="FechaCreado0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="HoraCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IdTipoTercero" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoTercero" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_TipoTercero" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NivelRiesgo_TipoTercero" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdArea" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Area" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_Area" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NivelRiesgo_Area" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdPosicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pocision" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_Posicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NivelRiesgo_Pocision" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdNivelAcademico" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NivelAcademico" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_NivelAcademico" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NivelRiesgo_NivelAcademico" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdPaisProcedencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaisProcedencia" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_PaisProcedencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NivelRiesgo_PaisProcedencia" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdPaisResidencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaisResidencia" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_PaisResidencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NivelRiesgoPaisResidencia" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdProvincia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Provincia" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_Provincia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NivelRiesgo_Provincia" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdSalarioDevengado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SalarioDevengado" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_SalarioDevengado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NivelRiesgoSalarioDevengado" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="ActividadSegundaria" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="NivelRiesgo_ActividadSegundaria" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_ActividadSegundaria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IngresosAdicionales" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_IngresosAdicionales" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NivelRiesgo_IngresosAdicionales" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdPEP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PEP" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_PEP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NivelRiesgoPEP" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="PrimaAnual" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_PrimaAnual" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NivelRisgoPrimaAnual" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdTipoMonitoreo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoMonitoreo" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdTipoDebidaDiligencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdNivel_Riesgo_Consolidado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NivelRiesgoConsolidado" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Observaciones" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>