<?xml version="1.0" encoding="utf-8"?><Database Name="SysFlexSeguros" Class="BDConexionMantenimientosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.25.24.3;Initial Catalog=SysFlexSeguros;User ID=sa" SettingsObjectName="UtilidadesAmigos.Data.Properties.Settings" SettingsPropertyName="SysFlexSegurosConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="Utililades.SP_BUSCA_OFICINAS" Method="SP_BUSCA_OFICINAS">
    <Parameter Name="IdOficina" Parameter="idOficina" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdSucursal" Parameter="idSucursal" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_BUSCA_OFICINASResult">
      <Column Name="IdOficina" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdSucursal" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Sucursal" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Creadopor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MANTENIMIENTO_OFICINAS" Method="SP_MANTENIMIENTO_OFICINAS">
    <Parameter Name="IdOficina" Parameter="idOficina" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdSucursal" Parameter="idSucursal" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_OFICINASResult">
      <Column Name="IdOficina" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="IdSucursal" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MAN_BUSCA_DEPARTAMENTOS" Method="SP_MAN_BUSCA_DEPARTAMENTOS">
    <Parameter Name="IdSucursal" Parameter="idSucursal" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdOficina" Parameter="idOficina" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdDepartamento" Parameter="idDepartamento" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_MAN_BUSCA_DEPARTAMENTOSResult">
      <Column Name="IdSucursal" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Sucursal" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdOficina" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdDepartamento" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Departamento" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MAN_MANTENIMIENTO_DEPARTAMENTOS" Method="SP_MAN_MANTENIMIENTO_DEPARTAMENTOS">
    <Parameter Name="IdSucursal" Parameter="idSucursal" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdOficina" Parameter="idOficina" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdDepartamento" Parameter="idDepartamento" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UsuarioAdiciona" Parameter="usuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MAN_MANTENIMIENTO_DEPARTAMENTOSResult">
      <Column Name="IdSucursal" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdOficina" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="IdDepartamento" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MAN_MANTENIMIENTO_EMPLEADO" Method="SP_MAN_MANTENIMIENTO_EMPLEADO">
    <Parameter Name="IdSucursal" Parameter="idSucursal" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdOfiicna" Parameter="idOfiicna" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdDepartamento" Parameter="idDepartamento" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdEmpleado" Parameter="idEmpleado" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MAN_MANTENIMIENTO_EMPLEADOResult">
      <Column Name="IdSucursal" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdOfiicna" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="IdDepartamento" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="IdEmpleado" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MAN_BUSCA_EMPLEADOS" Method="SP_MAN_BUSCA_EMPLEADOS">
    <Parameter Name="IdSucursal" Parameter="idSucursal" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdOficina" Parameter="idOficina" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdDepartamento" Parameter="idDepartamento" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdEmpleado" Parameter="idEmpleado" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_MAN_BUSCA_EMPLEADOSResult">
      <Column Name="IdSucursal" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Sucursal" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdOfiicna" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdDepartamento" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Departamento" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdEmpleado" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_PORCIENTO_COMISION_POR_DEFECTO" Method="SP_BUSCA_PORCIENTO_COMISION_POR_DEFECTO">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Subramo" Parameter="subramo" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="SP_BUSCA_PORCIENTO_COMISION_POR_DEFECTOResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ramo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CodSubramo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subramo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PorcientoComision" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MANTENIMIENTO_COMISIONES_POR_DEFECTO" Method="SP_MANTENIMIENTO_COMISIONES_POR_DEFECTO">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubRamo" Parameter="subRamo" Type="System.Int32" DbType="Int" />
    <Parameter Name="PorcientoComision" Parameter="porcientoComision" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_COMISIONES_POR_DEFECTOResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Ramo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PorcientoComision" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_LISTADO_INTERMEDIARIOS" Method="SP_BUSCA_LISTADO_INTERMEDIARIOS">
    <Parameter Name="CodigoIntermediario" Parameter="codigoIntermediario" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="NombreIntermediario" Parameter="nombreIntermediario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodigoSupervisor" Parameter="codigoSupervisor" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="NombreSupervisor" Parameter="nombreSupervisor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Oficin" Parameter="oficin" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_LISTADO_INTERMEDIARIOSResult">
      <Column Name="Compania" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Codigo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cuenta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Auxiliar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoRnc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescripcionTipoRNC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Rnc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NombreVendedor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="PorcientoComision" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="CodigoSupervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_Entrada" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaEntrada" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PorcientoGastos" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="nota" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="tipo_Intermediario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Agencia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Fec_Nac" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="Publicidad" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PagoComPor" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Banco" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreBanco" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CtaBanco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodigoRnc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Retencion" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PorcDescuento" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="SupervisorCrea" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VendedorCrea" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Ubicacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescripcionUbicacion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TelefonoOficina" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Beeper" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LicenciaSeguro" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodigoAnterior" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Oficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreOficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoCuentaBco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EjecutivoServicio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AsumeCxc" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CodigoCliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Record_Id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PorcientoCapitalizacion" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Gestor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EjecutivoCobros" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiasCancelacionAutomatica" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CodigoSupervisor1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreSupervisor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCAR_COMISIONES_INTERMEDIARIO" Method="SP_BUSCAR_COMISIONES_INTERMEDIARIO">
    <Parameter Name="CodigoIntermediario" Parameter="codigoIntermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubRamo" Parameter="subRamo" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCAR_COMISIONES_INTERMEDIARIOResult">
      <Column Name="Codigo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IdRamo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ramo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdSubRamo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subramo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PorcientoComision" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MANTENIMIENTO_PORCIENTO_COMISION_INTERMEDIARIO_SELECCIONADO" Method="SP_MANTENIMIENTO_PORCIENTO_COMISION_INTERMEDIARIO_SELECCIONADO">
    <Parameter Name="Compania" Parameter="compania" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="Codigo" Parameter="codigo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubRamo" Parameter="subRamo" Type="System.Int32" DbType="Int" />
    <Parameter Name="PorcientoComision" Parameter="porcientoComision" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="PorcientoGastos" Parameter="porcientoGastos" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="PorcientoNivel1" Parameter="porcientoNivel1" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="PorcientoNivel2" Parameter="porcientoNivel2" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Record_Id" Parameter="record_Id" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SP_MANTENIMIENTO_PORCIENTO_COMISION_INTERMEDIARIO_SELECCIONADOResult">
      <Column Name="Compania" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Codigo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ramo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PorcientoComision" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoGastos" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoNivel1" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoNivel2" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Record_Id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MANTENIMIENTO_INTERMEDIARIOS_SUPERVISORES" Method="SP_MANTENIMIENTO_INTERMEDIARIOS_SUPERVISORES">
    <Parameter Name="Compania" Parameter="compania" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="Codigo" Parameter="codigo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cuenta" Parameter="cuenta" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Auxiliar" Parameter="auxiliar" Type="System.Int32" DbType="Int" />
    <Parameter Name="TipoRnc" Parameter="tipoRnc" Type="System.Int32" DbType="Int" />
    <Parameter Name="Rnc" Parameter="rnc" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PorcientoComision" Parameter="porcientoComision" Type="System.Decimal" DbType="Decimal(3,2)" />
    <Parameter Name="CodigoSupervisor" Parameter="codigoSupervisor" Type="System.Int32" DbType="Int" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="Fecha_Entrada" Parameter="fecha_Entrada" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UsuarioProcesa" Parameter="usuarioProcesa" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="PorcientoGastos" Parameter="porcientoGastos" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="tipo_Intermediario" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Agencia" Parameter="agencia" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Fec_Nac" Parameter="fec_Nac" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Publicidad" Parameter="publicidad" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="PagoComPor" Parameter="pagoComPor" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Banco" Parameter="banco" Type="System.Int32" DbType="Int" />
    <Parameter Name="CtaBanco" Parameter="ctaBanco" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CodigoRnc" Parameter="codigoRnc" Type="System.Int32" DbType="Int" />
    <Parameter Name="Retencion" Parameter="retencion" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="PorcDescuento" Parameter="porcDescuento" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="SupervisorCrea" Parameter="supervisorCrea" Type="System.Int32" DbType="Int" />
    <Parameter Name="VendedorCrea" Parameter="vendedorCrea" Type="System.Int32" DbType="Int" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Ubicacion" Parameter="ubicacion" Type="System.Int32" DbType="Int" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="TelefonoOficina" Parameter="telefonoOficina" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Celular" Parameter="celular" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Beeper" Parameter="beeper" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="LicenciaSeguro" Parameter="licenciaSeguro" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CodigoAnterior" Parameter="codigoAnterior" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Oficina" Parameter="oficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="TipoCuentaBco" Parameter="tipoCuentaBco" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="EjecutivoServicio" Parameter="ejecutivoServicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="AsumeCxc" Parameter="asumeCxc" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="CodigoCliente" Parameter="codigoCliente" Type="System.Int32" DbType="Int" />
    <Parameter Name="Record_Id" Parameter="record_Id" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="PorcientoCapitalizacion" Parameter="porcientoCapitalizacion" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Gestor" Parameter="gestor" Type="System.Int32" DbType="Int" />
    <Parameter Name="EjecutivoCobros" Parameter="ejecutivoCobros" Type="System.Int32" DbType="Int" />
    <Parameter Name="DiasCancelacionAutomatica" Parameter="diasCancelacionAutomatica" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_INTERMEDIARIOS_SUPERVISORESResult">
      <Column Name="Compania" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Codigo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cuenta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Auxiliar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoRnc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Rnc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NombreVendedor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="PorcientoComision" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="CodigoSupervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Fecha_Entrada" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PorcientoGastos" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="nota" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="tipo_Intermediario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Agencia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Fec_Nac" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Publicidad" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PagoComPor" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Banco" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CtaBanco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodigoRnc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Retencion" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PorcDescuento" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="SupervisorCrea" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VendedorCrea" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Ubicacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TelefonoOficina" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Beeper" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LicenciaSeguro" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodigoAnterior" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Oficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoCuentaBco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EjecutivoServicio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AsumeCxc" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CodigoCliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Record_Id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PorcientoCapitalizacion" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Gestor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EjecutivoCobros" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiasCancelacionAutomatica" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_SACAR_CODIGO_MAXIMO_INTERMEDIARIO" Method="SP_SACAR_CODIGO_MAXIMO_INTERMEDIARIO">
    <ElementType Name="SP_SACAR_CODIGO_MAXIMO_INTERMEDIARIOResult">
      <Column Name="Codigo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_GUARDAR_CADENA_DETALLE_INTERMEDIARIO" Method="SP_GUARDAR_CADENA_DETALLE_INTERMEDIARIO">
    <Parameter Name="Compania" Parameter="compania" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdIntermediario" Parameter="idIntermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdIntermediarioSupervisa" Parameter="idIntermediarioSupervisa" Type="System.Int32" DbType="Int" />
    <Parameter Name="UsuarioAdiciona" Parameter="usuarioAdiciona" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_CADENA_DETALLE_INTERMEDIARIOResult">
      <Column Name="Compania" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdIntermediarioSupervisa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MANTENIMIENTO_PROCEEDORES_SOLICITUD" Method="SP_MANTENIMIENTO_PROCEEDORES_SOLICITUD">
    <Parameter Name="Compania" Parameter="compania" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="Codigo" Parameter="codigo" Type="System.Int32" DbType="Int" />
    <Parameter Name="TipoCliente" Parameter="tipoCliente" Type="System.Int32" DbType="Int" />
    <Parameter Name="TipoRnc" Parameter="tipoRnc" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="RNC" Parameter="rNC" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NombreCliente" Parameter="nombreCliente" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Ubicacion" Parameter="ubicacion" Type="System.Int32" DbType="Int" />
    <Parameter Name="LimiteCredito" Parameter="limiteCredito" Type="System.Decimal" DbType="Decimal(19,2)" />
    <Parameter Name="Descuento" Parameter="descuento" Type="System.Decimal" DbType="Decimal(19,2)" />
    <Parameter Name="CondicionPago" Parameter="condicionPago" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="FechaUltPago" Parameter="fechaUltPago" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="MontoUltPago" Parameter="montoUltPago" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Balance" Parameter="balance" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="UsuarioAdiciona" Parameter="usuarioAdiciona" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FechaAdiciona" Parameter="fechaAdiciona" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UsuarioModifica" Parameter="usuarioModifica" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FechaModifica" Parameter="fechaModifica" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="CodigoRnc" Parameter="codigoRnc" Type="System.Int32" DbType="Int" />
    <Parameter Name="PorcComision" Parameter="porcComision" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodMoneda" Parameter="codMoneda" Type="System.Int32" DbType="Int" />
    <Parameter Name="TelefonoCasa" Parameter="telefonoCasa" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TelefonoOficina" Parameter="telefonoOficina" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Celular" Parameter="celular" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Beeper" Parameter="beeper" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoPago" Parameter="tipoPago" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="Banco" Parameter="banco" Type="System.Int32" DbType="Int" />
    <Parameter Name="CuentaBanco" Parameter="cuentaBanco" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Contacto" Parameter="contacto" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TipoCuentaBanco" Parameter="tipoCuentaBanco" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ClaseProveedor" Parameter="claseProveedor" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_PROCEEDORES_SOLICITUDResult">
      <Column Name="Compania" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Codigo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoCliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoRnc" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NombreCliente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Ubicacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LimiteCredito" Type="System.Decimal" DbType="Decimal(19,2)" CanBeNull="true" />
      <Column Name="Descuento" Type="System.Decimal" DbType="Decimal(19,2)" CanBeNull="true" />
      <Column Name="CondicionPago" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="FechaUltPago" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MontoUltPago" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CodigoRnc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PorcComision" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CodMoneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TelefonoCasa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TelefonoOficina" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Beeper" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Banco" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CuentaBanco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contacto" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TipoCuentaBanco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClaseProveedor" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCAR_PROVEEDOR_SOLICITUD_CHEQUE" Method="SP_BUSCAR_PROVEEDOR_SOLICITUD_CHEQUE">
    <Parameter Name="Codigo" Parameter="codigo" Type="System.Int32" DbType="Int" />
    <Parameter Name="RNC" Parameter="rNC" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_BUSCAR_PROVEEDOR_SOLICITUD_CHEQUEResult">
      <Column Name="Compania" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Codigo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TipoCliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoRnc" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NombreCliente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Ubicacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LimiteCredito" Type="System.Decimal" DbType="Decimal(19,2)" CanBeNull="true" />
      <Column Name="Descuento" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CondicionPago" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="FechaUltPago" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MontoUltPago" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CodigoRnc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PorcComision" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CodMoneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TelefonoCasa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TelefonoOficina" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Beeper" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Banco" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CuentaBanco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contacto" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TipoCuentaBanco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClaseProveedor" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_MONTOS_SOLICITUD_CHEQUES" Method="SP_BUSCA_MONTOS_SOLICITUD_CHEQUES">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoIntermediario" Parameter="codigoIntermediario" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_MONTOS_SOLICITUD_CHEQUESResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bruto" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Neto" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Comision" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Retencion" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Avance" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="ALiquidar" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_MONTOS_SOLICITUD_CHEQUE" Method="SP_PROCESAR_MONTOS_SOLICITUD_CHEQUE">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoIntermediario" Parameter="codigoIntermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Bruto" Parameter="bruto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Neto" Parameter="neto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Comision" Parameter="comision" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Retencion" Parameter="retencion" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Avance" Parameter="avance" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ALiquidar" Parameter="aLiquidar" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_MONTOS_SOLICITUD_CHEQUEResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bruto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Neto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Comision" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Retencion" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Avance" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ALiquidar" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_SOLICITUD_CHEQUE" Method="SP_PROCESAR_SOLICITUD_CHEQUE">
    <Parameter Name="Solicitud" Parameter="solicitud" Type="System.Int32" DbType="Int" />
    <Parameter Name="RNCTipo" Parameter="rNCTipo" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="RNC" Parameter="rNC" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CodigoBeneficiario" Parameter="codigoBeneficiario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Endosable" Parameter="endosable" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="CtaBanco" Parameter="ctaBanco" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="CuentaBanco" Parameter="cuentaBanco" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Valor" Parameter="valor" Type="System.Decimal" DbType="Money" />
    <Parameter Name="UsuarioProcesa" Parameter="usuarioProcesa" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="TotalCobradoVendedor" Parameter="totalCobradoVendedor" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ComisionBrutaVendedor" Parameter="comisionBrutaVendedor" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="RetencionVendedor" Parameter="retencionVendedor" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_SOLICITUD_CHEQUEResult">
      <Column Name="Compania" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Anulado" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Sistema" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Solicitud" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoSolicitud" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DescTipoSolicitud" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaSolicitud" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sucursal" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DescSucursal" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Departamento" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DescDepto" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Seccion" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DescSeccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RNCTipo" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodigoBeneficiario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Beneficiario1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Beneficiario2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Endosable" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="CtaBanco" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CuentaBanco" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Valor" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Concepto1" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Concepto2" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="NumeroCheque" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaCheque" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AnoMesConciliado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaConciliado" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioDigita" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FechaDigita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Aprobado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaAprobado" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioCheque" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PrimeraFirma" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SegundaFirma" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UsuarioCancel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Impresion" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="TipoDoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_SACAR_ULTIMO_NUMERO_SOLICITUD_GENERADO" Method="SP_SACAR_ULTIMO_NUMERO_SOLICITUD_GENERADO">
    <Parameter Name="CodigoProveedor" Parameter="codigoProveedor" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_SACAR_ULTIMO_NUMERO_SOLICITUD_GENERADOResult">
      <Column Name="NumeroSolicitud" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_DATOS_SOLICITUD_CHEQUES_CUENTAS" Method="SP_PROCESAR_DATOS_SOLICITUD_CHEQUES_CUENTAS">
    <Parameter Name="Solicitud" Parameter="solicitud" Type="System.Int32" DbType="Int" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cuenta" Parameter="cuenta" Type="System.String" DbType="NVarChar(28)" />
    <Parameter Name="Auxiliar" Parameter="auxiliar" Type="System.Int32" DbType="Int" />
    <Parameter Name="Origen" Parameter="origen" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="Valor" Parameter="valor" Type="System.Decimal" DbType="Money" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_DATOS_SOLICITUD_CHEQUES_CUENTASResult">
      <Column Name="Compania" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Anulado" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Sistema" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Solicitud" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cuenta" Type="System.String" DbType="NVarChar(28)" CanBeNull="true" />
      <Column Name="Auxiliar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescCuenta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Origen" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Valor" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TipoCompromiso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Departamento" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_REPORTE_ANTIGUEDAD_SALDO" Method="SP_PROCESAR_INFORMACION_REPORTE_ANTIGUEDAD_SALDO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaCorte" Parameter="fechaCorte" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DocumentoFormateado" Parameter="documentoFormateado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DocumentoFiltro" Parameter="documentoFiltro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.Int32" DbType="Int" />
    <Parameter Name="DescripcionTipo" Parameter="descripcionTipo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Asegurado" Parameter="asegurado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodCliente" Parameter="codCliente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaFactura" Parameter="fechaFactura" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Intermediario" Parameter="intermediario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodIntermediario" Parameter="codIntermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodMoneda" Parameter="codMoneda" Type="System.Int32" DbType="Int" />
    <Parameter Name="DescripcionMoneda" Parameter="descripcionMoneda" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="CodRamo" Parameter="codRamo" Type="System.Int32" DbType="Int" />
    <Parameter Name="InicioVigencia" Parameter="inicioVigencia" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Inicio" Parameter="inicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FinVigencia" Parameter="finVigencia" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Fin" Parameter="fin" Type="System.DateTime" DbType="Date" />
    <Parameter Name="CodOficina" Parameter="codOficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="Oficina" Parameter="oficina" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="dias" Type="System.Int32" DbType="Int" />
    <Parameter Name="Facturado" Parameter="facturado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Cobrado" Parameter="cobrado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Balance" Parameter="balance" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Impuesto" Parameter="impuesto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="PorcientoComision" Parameter="porcientoComision" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ValorComision" Parameter="valorComision" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ComisionPendiente" Parameter="comisionPendiente" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="_0_10" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="_0_30" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="_31_60" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="_61_90" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="_91_120" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="_121_150" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="_151_mas" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Total" Parameter="total" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Diferencia" Parameter="diferencia" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="OrigenTipo" Parameter="origenTipo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_REPORTE_ANTIGUEDAD_SALDOResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaCorte" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DocumentoFormateado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DocumentoFiltro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Tipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescripcionTipo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Asegurado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodCliente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaFactura" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodMoneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescripcionMoneda" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CodRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Inicio" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Fin" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CodOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="dias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Facturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoComision" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ValorComision" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ComisionPendiente" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_0_10]" Member="_0_10" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_0_30]" Member="_0_30" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_31_60]" Member="_31_60" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_61_90]" Member="_61_90" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_91_120]" Member="_91_120" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_121_150]" Member="_121_150" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_151_mas]" Member="_151_mas" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Diferencia" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="OrigenTipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_CONSULTAR_DATOS_ANTIGUEDAD_SALDO" Method="SP_CONSULTAR_DATOS_ANTIGUEDAD_SALDO">
    <Parameter Name="FechaCorte" Parameter="fechaCorte" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_CONSULTAR_DATOS_ANTIGUEDAD_SALDOResult">
      <Column Name="Documento" Type="System.String" DbType="VarChar(37) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroFacturaFiltro" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Tipo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DescripcionTipo" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Asegurado" Type="System.String" DbType="VarChar(288) NOT NULL" CanBeNull="false" />
      <Column Name="ClienteFiltro" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(233) NOT NULL" CanBeNull="false" />
      <Column Name="VendedorFiltro" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodMoneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescripcionMoneda" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescripcionRamo" Type="System.String" DbType="NVarChar(83) NOT NULL" CanBeNull="false" />
      <Column Name="InicioVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Inicio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Fin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CodOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Dias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Facturado" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PorcComision" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ValorComision" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ComisionPendiente" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[0-10]" Member="_0_10" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[0-30]" Member="_0_30" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[31-60]" Member="_31_60" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[61-90]" Member="_61_90" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[91-120]" Member="_91_120" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[121-150]" Member="_121_150" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[151-MAS]" Member="_151_MAS" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Diferencia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrdenTipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_SACAR_TASA_MONEDA" Method="SP_SACAR_TASA_MONEDA">
    <Parameter Name="CodigoMoneda" Parameter="codigoMoneda" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_SACAR_TASA_MONEDAResult">
      <Column Name="Prima" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_REPORTE_ANTIDAD_SALDO_DETALLE" Method="SP_REPORTE_ANTIDAD_SALDO_DETALLE">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TasaDollar" Parameter="tasaDollar" Type="System.Decimal" DbType="Decimal(20,2)" />
    <ElementType Name="SP_REPORTE_ANTIDAD_SALDO_DETALLEResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Persona" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FechaCorte" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DocumentoFormateado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DocumentoFiltro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Tipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescripcionTipo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Asegurado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodCliente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaFactura" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodMoneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescripcionMoneda" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CodRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ramo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Inicio" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Fin" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CodOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="dias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Facturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoComision" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ValorComision" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ComisionPendiente" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_0_10]" Member="_0_10" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_0_30]" Member="_0_30" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_31_60]" Member="_31_60" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_61_90]" Member="_61_90" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_91_120]" Member="_91_120" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_121_150]" Member="_121_150" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_151_mas]" Member="_151_mas" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Diferencia" Type="System.Decimal" DbType="Decimal(21,2)" CanBeNull="true" />
      <Column Name="OrigenTipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPesos" Type="System.Decimal" DbType="Decimal(38,4)" CanBeNull="true" />
      <Column Name="CantidadFactura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadCreditos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadPrimaDeposito" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_REPORTE_ANTIDAD_SALDO_RESUMIDO" Method="SP_REPORTE_ANTIDAD_SALDO_RESUMIDO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TasaDollar" Parameter="tasaDollar" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="SuperResumido" Parameter="superResumido" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_REPORTE_ANTIDAD_SALDO_RESUMIDOResult">
      <Column Name="CodMoneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaCorte" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DescripcionMoneda" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Ramo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CodRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadFactura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadCreditos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadPrimaDeposito" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[_0_30]" Member="_0_30" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[_31_60]" Member="_31_60" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[_61_90]" Member="_61_90" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[_91_120]" Member="_91_120" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[_121_150]" Member="_121_150" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[_151_Mas]" Member="_151_Mas" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="GeneradoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="TotalPesos" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Tasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_REGISTROS_SOLICITUD_CHEQUE_LOTE" Method="SP_PROCESAR_INFORMACION_REGISTROS_SOLICITUD_CHEQUE_LOTE">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdUsuairo" Parameter="idUsuairo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoIntermediario" Parameter="codigoIntermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroSolicitud" Parameter="numeroSolicitud" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="MontoSolicitud" Parameter="montoSolicitud" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_REGISTROS_SOLICITUD_CHEQUE_LOTEResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdUsuairo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumeroSolicitud" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaProceso" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaDesde" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaHasta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MontoSolicitud" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_REGISTROS_SOLICITUD_CHEQUE_LOTE" Method="SP_BUSCA_REGISTROS_SOLICITUD_CHEQUE_LOTE">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="SP_BUSCA_REGISTROS_SOLICITUD_CHEQUE_LOTEResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuairo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CodigoIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="NumeroSolicitud" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaProceso0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaProceso" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FechaDesde" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ValidadoDesde" Type="System.String" DbType="VarChar(98) NOT NULL" CanBeNull="false" />
      <Column Name="FechaHasta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ValidadoHasta" Type="System.String" DbType="VarChar(89) NOT NULL" CanBeNull="false" />
      <Column Name="MontoSolicitud" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="CantidadProcesados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadDescartados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_REPORTE_ANTIGUEDAD_SALDO_NETEADO_DETALLE" Method="SP_BUSCA_REPORTE_ANTIGUEDAD_SALDO_NETEADO_DETALLE">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Tasa" Parameter="tasa" Type="System.Decimal" DbType="Decimal(20,2)" />
    <ElementType Name="SP_BUSCA_REPORTE_ANTIGUEDAD_SALDO_NETEADO_DETALLEResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="GeneradoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FechaCorte" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaCorteFormateado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Asegurado" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Asegurado1" Type="System.String" DbType="VarChar(288) NOT NULL" CanBeNull="false" />
      <Column Name="CodCliente" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CodIntermediario" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodMoneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescripcionMoneda" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CodRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ramo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Inicio" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Fin" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Facturado" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="ValorComision" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="ComisionPendiente" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[_0_30]" Member="_0_30" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[_31_60]" Member="_31_60" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[_61_90]" Member="_61_90" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[_91_120]" Member="_91_120" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[_121_150]" Member="_121_150" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[_151_mas]" Member="_151_mas" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalPesos" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TasaDollar" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Diferencia" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_HISTORIAL_DATOS_ANTIGUEDAD_SALDO" Method="SP_PROCESAR_INFORMACION_HISTORIAL_DATOS_ANTIGUEDAD_SALDO">
    <Parameter Name="NoRegistro" Parameter="noRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaGuardado" Parameter="fechaGuardado" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaCorte" Parameter="fechaCorte" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DocumentoFormateado" Parameter="documentoFormateado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DocumentoFiltro" Parameter="documentoFiltro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.Int32" DbType="Int" />
    <Parameter Name="DocumentoTipo" Parameter="documentoTipo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Asegurado" Parameter="asegurado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodCliente" Parameter="codCliente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaFactura" Parameter="fechaFactura" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Intermediario" Parameter="intermediario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodIntermediario" Parameter="codIntermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodMoneda" Parameter="codMoneda" Type="System.Int32" DbType="Int" />
    <Parameter Name="DescripcionMoneda" Parameter="descripcionMoneda" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CodRamo" Parameter="codRamo" Type="System.Int32" DbType="Int" />
    <Parameter Name="InicioVigencia" Parameter="inicioVigencia" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Inicio" Parameter="inicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FinVigencia" Parameter="finVigencia" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Fin" Parameter="fin" Type="System.DateTime" DbType="Date" />
    <Parameter Name="CodOficina" Parameter="codOficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="Oficina" Parameter="oficina" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Dias" Parameter="dias" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Facturado" Parameter="facturado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Cobrado" Parameter="cobrado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Balance" Parameter="balance" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Impuesto" Parameter="impuesto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="PorcientoComision" Parameter="porcientoComision" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ValorComision" Parameter="valorComision" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ComisionPendiente" Parameter="comisionPendiente" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="_0_10" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="_0_30" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="_31_60" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="_61_90" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="_91_120" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="_121_150" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="_151_Mas" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Total" Parameter="total" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Diferencia" Parameter="diferencia" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="OrigenTipo" Parameter="origenTipo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_HISTORIAL_DATOS_ANTIGUEDAD_SALDOResult">
      <Column Name="NoRegistro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaGuardado" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaCorte" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DocumentoFormateado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DocumentoFiltro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Tipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DocumentoTipo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Asegurado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodCliente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaFactura" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodMoneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescripcionMoneda" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CodRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Inicio" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Fin" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CodOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Dias" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Facturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PorcientoComision" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ValorComision" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ComisionPendiente" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_0_10]" Member="_0_10" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_0_30]" Member="_0_30" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_31_60]" Member="_31_60" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_61_90]" Member="_61_90" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_91_120]" Member="_91_120" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_121_150]" Member="_121_150" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[_151_Mas]" Member="_151_Mas" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Diferencia" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="OrigenTipo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>