<?xml version="1.0" encoding="utf-8"?><Database Name="SysFlexSeguros" Class="BDConexionConsultaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.25.24.3;Initial Catalog=SysFlexSeguros;Integrated Security=False;User ID=sa" SettingsObjectName="UtilidadesAmigos.Data.Properties.Settings" SettingsPropertyName="SysFlexSegurosConnectionString2" Provider="System.Data.SqlClient" />
  <Function Name="Utililades.SP_BUSCAR_INFORMACION_POLIZA_GESTION_COBRO" Method="SP_BUSCAR_INFORMACION_POLIZA_GESTION_COBRO">
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CodigoCliente" Parameter="codigoCliente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCAR_INFORMACION_POLIZA_GESTION_COBROResult">
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ramo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Subramo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CodigoRamo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CodigoSubRamo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SumaAsegurada" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Cliente" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NombreCliente" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Telefonos" Type="System.String" DbType="VarChar(203) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(233) NOT NULL" CanBeNull="false" />
      <Column Name="LicenciaSeguro" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodigoSupervisor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(233) NOT NULL" CanBeNull="false" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreada" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FechaInicioVigencia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FechaFinVigencia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Facturado" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalFacturas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalRecibos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalReclamaciones" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACON_REPORTE_COMENTARIO_GESTION_COBRO" Method="SP_PROCESAR_INFORMACON_REPORTE_COMENTARIO_GESTION_COBRO">
    <Parameter Name="NumeroRegistro" Parameter="numeroRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaProceso" Parameter="fechaProceso" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Hora" Parameter="hora" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="CantidadRegistros" Parameter="cantidadRegistros" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUsuarioGenera" Parameter="idUsuarioGenera" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACON_REPORTE_COMENTARIO_GESTION_COBROResult">
      <Column Name="NumeroRegistro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaProceso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdUsuarioGenera" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_COBERTURA_VALIDACION_ARCHIVO" Method="SP_PROCESAR_INFORMACION_COBERTURA_VALIDACION_ARCHIVO">
    <Parameter Name="NumeroRegistro" Parameter="numeroRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdUauario" Parameter="idUauario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Chasis" Parameter="chasis" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Placa" Parameter="placa" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Cobertura" Parameter="cobertura" Type="System.String" DbType="VarChar(300)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_COBERTURA_VALIDACION_ARCHIVOResult">
      <Column Name="NumeroRegistro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdUaurioProceso" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Chasis" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Placa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cobertura" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_VALIDACION_COBERTURA_SISTEMA" Method="SP_PROCESAR_INFORMACION_VALIDACION_COBERTURA_SISTEMA">
    <Parameter Name="NumeroRegistro" Parameter="numeroRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Items" Parameter="items" Type="System.Int32" DbType="Int" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="Cliente" Parameter="cliente" Type="System.String" DbType="VarChar(300)" />
    <Parameter Name="NombreCliente" Parameter="nombreCliente" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="ApellidoCliente" Parameter="apellidoCliente" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="Ciudad" Parameter="ciudad" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="DireccionCliente" Parameter="direccionCliente" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoIdentificacion" Parameter="tipoIdentificacion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Intermediario" Parameter="intermediario" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="FechaInicioVigencia" Parameter="fechaInicioVigencia" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FechaFinVigencia" Parameter="fechaFinVigencia" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="InicioVigencia" Parameter="inicioVigencia" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="FinVigencia" Parameter="finVigencia" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="FechaProceso" Parameter="fechaProceso" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="FechaProcesoBruto" Parameter="fechaProcesoBruto" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="MesValidado" Parameter="mesValidado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoVehiculo" Parameter="tipoVehiculo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Marca" Parameter="marca" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Modelo" Parameter="modelo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Capacidad" Parameter="capacidad" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Ano" Parameter="ano" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Color" Parameter="color" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Chasis" Parameter="chasis" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Placa" Parameter="placa" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ValorAsegurado" Parameter="valorAsegurado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Cobertura" Parameter="cobertura" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoMovimiento" Parameter="tipoMovimiento" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CantidadRegistros" Parameter="cantidadRegistros" Type="System.Int32" DbType="Int" />
    <Parameter Name="ValidadoDesde" Parameter="validadoDesde" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ValidadoHasta" Parameter="validadoHasta" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="GeneradoPor" Parameter="generadoPor" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Oficina" Parameter="oficina" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_VALIDACION_COBERTURA_SISTEMAResult">
      <Column Name="NumeroRegistro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Items" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="NombreCliente" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ApellidoCliente" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DireccionCliente" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="FechaInicioVigencia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaFinVigencia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FechaProceso" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FechaProcesoBruto" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MesValidado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoVehiculo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Modelo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Capacidad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ano" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Chasis" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Placa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ValorAsegurado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cobertura" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoMovimiento" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValidadoDesde" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ValidadoHasta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GeneradoPor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_CONCEPTO_LLAMADA" Method="SP_BUSCA_CONCEPTO_LLAMADA">
    <Parameter Name="IdConceptoLlamada" Parameter="idConceptoLlamada" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdEstatusLlamada" Parameter="idEstatusLlamada" Type="System.Int32" DbType="Int" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_BUSCA_CONCEPTO_LLAMADAResult">
      <Column Name="IdConceptoLlamada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdEstatusLlamada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EstatusLLamada" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ConceptoLLamada" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="AplicaParaAviso0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AplicaParaAviso" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_DATOS_VEHICULO_GESTION_COBRO" Method="SP_BUSCA_DATOS_VEHICULO_GESTION_COBRO">
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SP_BUSCA_DATOS_VEHICULO_GESTION_COBROResult">
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Item" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Modelo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Ano" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Chasis" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Placa" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_GENERAR_REPORTE_GESTION_COBROS_FINAL" Method="SP_GENERAR_REPORTE_GESTION_COBROS_FINAL">
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdUsuarioCreo" Parameter="idUsuarioCreo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaProcesoDesde" Parameter="fechaProcesoDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaProcesoHasta" Parameter="fechaProcesoHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="UsuarioGenera" Parameter="usuarioGenera" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NOLLevaRangoFecha" Parameter="nOLLevaRangoFecha" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="SP_GENERAR_REPORTE_GESTION_COBROS_FINALResult">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FechaProceso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="IdEstatusLlamada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EstatusLlamada" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdConceptoLlamada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConceptoLlamada" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaFinVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NumeroSeguimiento" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ValidadoDesde" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="ValidadoHAsta" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="NoLLevaRangoFecha0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NoLlevaRangoFecha" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="GeneradoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_SACAR_CARTERA_EJECUTIVOS" Method="SP_SACAR_CARTERA_EJECUTIVOS">
    <Parameter Name="CodigoSupervisor" Parameter="codigoSupervisor" Type="System.Int32" DbType="Int" />
    <Parameter Name="CodigoIntermediario" Parameter="codigoIntermediario" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_SACAR_CARTERA_EJECUTIVOSResult">
      <Column Name="IdIntermediarioSupervisa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreSupervisor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IdIntermediario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreIntermediario" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="EstatusVendedor" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="TotalIntermediarios" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_SACAR_CARTERA_INTERMEDIARIOS" Method="SP_SACAR_CARTERA_INTERMEDIARIOS">
    <Parameter Name="Intermediario" Parameter="intermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="EstatusPoliza" Parameter="estatusPoliza" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="SP_SACAR_CARTERA_INTERMEDIARIOSResult">
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EstatusPoliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SumaAsegurada" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CodigoCliente" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreVendedor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="EstatusIntermediario" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Facturado" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="PolizasActivas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolizasCanceladas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolizasTransito" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolizasExclusion" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_COMENTARIO_POLIZA" Method="SP_PROCESAR_COMENTARIO_POLIZA">
    <Parameter Name="ID" Parameter="iD" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdEstatusLlamada" Parameter="idEstatusLlamada" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdConceptoLlamada" Parameter="idConceptoLlamada" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaFinVigencia" Parameter="fechaFinVigencia" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="NumeroSeguimiento" Parameter="numeroSeguimiento" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaNuevaLlamada" Parameter="fechaNuevaLlamada" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Hora" Parameter="hora" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_COMENTARIO_POLIZAResult">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaProceso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdEstatusLlamada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdConceptoLlamada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaFinVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NumeroSeguimiento" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaNuevaLlamada" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_POLIZAS_PARA_AVISO_GESTION_COBROS" Method="SP_BUSCA_POLIZAS_PARA_AVISO_GESTION_COBROS">
    <Parameter Name="NumeroRegistro" Parameter="numeroRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdEstatusLlamada" Parameter="idEstatusLlamada" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdConceptoLlamada" Parameter="idConceptoLlamada" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaGuardadoDesde" Parameter="fechaGuardadoDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaGuardadoHasta" Parameter="fechaGuardadoHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="SP_BUSCA_POLIZAS_PARA_AVISO_GESTION_COBROSResult">
      <Column Name="NumeroRegistro" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdEstatusLlamada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EstatusLlamada" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdConceptoLlamada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConceptoLlamada" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FechaGuardado" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNuevaLLamada0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaNuevaLlamada" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="HoraNuevaLLamada" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NuevaLlamada" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="CantidadRegistrosNoProcesados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadRegistrosProcesados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadRegistrosNoProcesadosParametros" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadRegistrosProcesadosParametros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_POLIZAS_AVISO_GESTION_COBROS" Method="SP_PROCESAR_INFORMACION_POLIZAS_AVISO_GESTION_COBROS">
    <Parameter Name="NumeroRegistro" Parameter="numeroRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdEstatusLlamada" Parameter="idEstatusLlamada" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdConceptoLlamada" Parameter="idConceptoLlamada" Type="System.Int32" DbType="Int" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="InicioVigencia" Parameter="inicioVigencia" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="FinVigencia" Parameter="finVigencia" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FechaNuevaLlamada" Parameter="fechaNuevaLlamada" Type="System.DateTime" DbType="Date" />
    <Parameter Name="HoraNuevaLlamada" Parameter="horaNuevaLlamada" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_POLIZAS_AVISO_GESTION_COBROSResult">
      <Column Name="NumeroRegistro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IdEstatusLlamada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdConceptoLlamada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaGuardado" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FechaNuevaLlamada" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HoraNuevaLlamada" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_GENERAR_DETALLE_ESTADISTICA_RENOVACION" Method="SP_GENERAR_DETALLE_ESTADISTICA_RENOVACION">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_GENERAR_DETALLE_ESTADISTICA_RENOVACIONResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="GeneradoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodigoOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreRamo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoSubRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreSubramo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Prima" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="FechaInicioVigencia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaFinVigencia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CodigoIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CodigoSupervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CodigoCliente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TelefonoResidencia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TelefonoOficina" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Renovada" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MontoRenovado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cancelada" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MontoCancelado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ValidadoDesde" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ValidadoHasta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MOSTRAR_DATA_CARGADA_ESTADISTICA_RENOVACION" Method="SP_MOSTRAR_DATA_CARGADA_ESTADISTICA_RENOVACION">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_MOSTRAR_DATA_CARGADA_ESTADISTICA_RENOVACIONResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="GeneradoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodigoOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Ramo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreRamo" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Prima" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CodigoIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CodigoSupervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ValidadoDesde0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ValidadoHasta0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ValidadoDesde" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="ValidadoHasta" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="CantidadRenovadas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MontoRenovado" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="CantidadCanceladas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MontoCancelado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_ESTADISTICA_RENOVACION_ORIGEN" Method="SP_ESTADISTICA_RENOVACION_ORIGEN">
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Oficina" Parameter="oficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubRamo" Parameter="subRamo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Intermediario" Parameter="intermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Supervisor" Parameter="supervisor" Type="System.Int32" DbType="Int" />
    <Parameter Name="ExcluirMotores" Parameter="excluirMotores" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="SP_ESTADISTICA_RENOVACION_ORIGENResult">
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodigoOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ramo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Bruto" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CodigoIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodigoSupervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValidadoDesde" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ValidadoHasta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExcluirMotores" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_DATA_ESTADISTICA_RENOVACION" Method="SP_PROCESAR_DATA_ESTADISTICA_RENOVACION">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Cotizacion" Parameter="cotizacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CodigoOficina" Parameter="codigoOficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Prima" Parameter="prima" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="CodigoIntermediario" Parameter="codigoIntermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="CodigoSupervisor" Parameter="codigoSupervisor" Type="System.Int32" DbType="Int" />
    <Parameter Name="ValidadoDesde" Parameter="validadoDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ValidadoHasta" Parameter="validadoHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ExcluirMotores" Parameter="excluirMotores" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_DATA_ESTADISTICA_RENOVACIONResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodigoOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ramo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Prima" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CodigoIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodigoSupervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValidadoDesde" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ValidadoHasta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExcluirMotores" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MOSTRAR_ESTADISTICA_RENOVACION_AGRUPADA" Method="SP_MOSTRAR_ESTADISTICA_RENOVACION_AGRUPADA">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoAgrupacion" Parameter="tipoAgrupacion" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_MOSTRAR_ESTADISTICA_RENOVACION_AGRUPADAResult">
      <Column Name="Entidad" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Codigo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExcluirMotores" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="ValidadoDesde" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="ValidadoHasta" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="GeneradoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CantidadARenovar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MontoARenovar" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="CantidadRenovadas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MontoRenovado" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="CantidadCanceladas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MontoCancelado" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CantidadPendiente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MontoPendienteRenovar" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MOSTRAR_DETALLE_ESTADISTICA_RENOVACION" Method="SP_MOSTRAR_DETALLE_ESTADISTICA_RENOVACION">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_MOSTRAR_DETALLE_ESTADISTICA_RENOVACIONResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="GeneradoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TelefonoResidencia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TelefonoOficina" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodigoOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Ramo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreRamo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Prima" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CodigoIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CodigoSupervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ValidadoDesde0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ValidadoHasta0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ValidadoDesde" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="ValidadoHasta" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="ExcluirMotores0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ExcluirMotores" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="CantidadRenovadas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Renovada" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MontoRenovado" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="CantidadCanceladas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cancelada" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MontoCancelado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_GESTION_COBROS_COMENTARIO_POLIZA" Method="SP_BUSCA_GESTION_COBROS_COMENTARIO_POLIZA">
    <Parameter Name="ID" Parameter="iD" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaFinVigencia" Parameter="fechaFinVigencia" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="SP_BUSCA_GESTION_COBROS_COMENTARIO_POLIZAResult">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FechaProceso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="IdEstatusLlamada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EstatusLlamada" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdConceptoLlamada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConceptoLlamada" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaFinVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NumeroSeguimiento" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaNuevaLlamada0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaLlamada" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Hora1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_CLIENTE_SIN_POLIZAS" Method="SP_BUSCA_CLIENTE_SIN_POLIZAS">
    <Parameter Name="CodigoCliente" Parameter="codigoCliente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Numeroidentificacion" Parameter="numeroidentificacion" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Supervisor" Parameter="supervisor" Type="System.Int32" DbType="Int" />
    <Parameter Name="Intermediario" Parameter="intermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="NombreCliente" Parameter="nombreCliente" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_BUSCA_CLIENTE_SIN_POLIZASResult">
      <Column Name="Codigo" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(288) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CodigoSupervisor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CodigoIntermediario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(233) NOT NULL" CanBeNull="false" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(233) NOT NULL" CanBeNull="false" />
      <Column Name="Cobrador" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="fecha0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="TelefonoResidencia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TelefonoOficina" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Beeper" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nacionalidad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClaseCliente" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MOSTRAR_POLIZAS_SIN_IMPRESION_MARBETE" Method="SP_MOSTRAR_POLIZAS_SIN_IMPRESION_MARBETE">
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Supervisor" Parameter="supervisor" Type="System.Int32" DbType="Int" />
    <Parameter Name="Intermediario" Parameter="intermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Oficina" Parameter="oficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubRamo" Parameter="subRamo" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_MOSTRAR_POLIZAS_SIN_IMPRESION_MARBETEResult">
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Prima" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CodigoSupervisor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CodigoIntermediario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(233) NOT NULL" CanBeNull="false" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(233) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreadoFormateada" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CodigoRamo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ramo" Type="System.String" DbType="NVarChar(83) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoSubramo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubRamo" Type="System.String" DbType="NVarChar(83) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>