<?xml version="1.0" encoding="utf-8"?><Database Name="SysFlexSegurosNew" Class="BDCOnexionGerenciaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JDIAZ0624;Initial Catalog=SysFlexSegurosNew;User ID=juan.diaz;Encrypt=False" SettingsObjectName="UtilidadesAmigos.Data.Properties.Settings" SettingsPropertyName="SysFlexSegurosNewConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="Utililades.SP_BUSCA_ACUERDO_PAGO" Method="SP_BUSCA_ACUERDO_PAGO">
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Supervisor" Parameter="supervisor" Type="System.Int32" DbType="Int" />
    <Parameter Name="Intermediario" Parameter="intermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="GeneradoPor" Parameter="generadoPor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_ACUERDO_PAGOResult">
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ValorPoliza" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaFacturacion" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="TipoAcuerdo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Frecuencia" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreSupervisor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="NombreIntermediario" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="FrecuenciaPagos" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="CantidadCuotas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Inicial" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cuota" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="FechaC1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DiasC1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PagoC1" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="EstatusC1" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="FechaC2" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DiasC2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PagoC2" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="EstatusC2" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha3" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DiasC3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pago3" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="EstatusC3" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="FechaC4" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DiasC4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pago4" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DiasC5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaC5" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="EstatusC4" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="PagoC5" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="EstatusC5" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="FechaC6" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DiasC6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PagoC6" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="EstatusC6" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="PagadoTotal" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Pendiente" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ValidadoDesde" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ValidadoHasta" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="GeneradoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_GUARDAR_ANTIGUEDAD_POR_ATRASO" Method="SP_GUARDAR_ANTIGUEDAD_POR_ATRASO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Codigo_Intermediario" Parameter="codigo_Intermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Intermediario" Parameter="intermediario" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Codigo_Supervisor" Parameter="codigo_Supervisor" Type="System.Int32" DbType="Int" />
    <Parameter Name="Supervisor" Parameter="supervisor" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Codigo" Parameter="codigo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Cliente" Parameter="cliente" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Telefonos" Parameter="telefonos" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Fecha_Facturacion" Parameter="fecha_Facturacion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Inicio_Vigencia" Parameter="inicio_Vigencia" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Fin_Vigencia" Parameter="fin_Vigencia" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Fecha_Ultimo_Pago" Parameter="fecha_Ultimo_Pago" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DiasTranscurridos" Parameter="diasTranscurridos" Type="System.Int32" DbType="Int" />
    <Parameter Name="Dias_Transcurridos_Pago" Parameter="dias_Transcurridos_Pago" Type="System.Int32" DbType="Int" />
    <Parameter Name="Valor_Poliza" Parameter="valor_Poliza" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Total_Pagado" Parameter="total_Pagado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Balance_Pendiente" Parameter="balance_Pendiente" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubRamo" Parameter="subRamo" Type="System.Int32" DbType="Int" />
    <Parameter Name="NombreRamo" Parameter="nombreRamo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NombreSubRamo" Parameter="nombreSubRamo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Inicial" Parameter="inicial" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Inicial_Pagado" Parameter="inicial_Pagado" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Cuota" Parameter="cuota" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="C1_Pagada" Parameter="c1_Pagada" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="C1" Parameter="c1" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="C2_Pagada" Parameter="c2_Pagada" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="C2" Parameter="c2" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="C3_Pagada" Parameter="c3_Pagada" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="C3" Parameter="c3" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="C4_Pagada" Parameter="c4_Pagada" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="C4" Parameter="c4" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="C5_Pagada" Parameter="c5_Pagada" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="C5" Parameter="c5" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="TotalDescuento" Parameter="totalDescuento" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_GUARDAR_ANTIGUEDAD_POR_ATRASOResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Codigo_Intermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Codigo_Supervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Codigo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Telefonos" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Fecha_Facturacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Inicio_Vigencia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fin_Vigencia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fecha_Ultimo_Pago" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiasTranscurridos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dias_Transcurridos_Pago" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Valor_Poliza" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total_Pagado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Balance_Pendiente" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Ramo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreRamo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NombreSubRamo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Inicial" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Inicial_Pagado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Cuota" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="C1_Pagada" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="C1" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="C2_Pagada" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="C2" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="C3_Pagada" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="C3" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="C4_Pagada" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="C4" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="C5_Pagada" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="C5" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalDescuento" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_REPORTE_ANTIGUEDAD_POR_ATRASO" Method="SP_REPORTE_ANTIGUEDAD_POR_ATRASO">
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubRamo" Parameter="subRamo" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_REPORTE_ANTIGUEDAD_POR_ATRASOResult">
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Codigo_Intermediario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Codigo_Supervisor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Codigo" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Telefonos" Type="System.String" DbType="VarChar(209) NOT NULL" CanBeNull="false" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fecha_Facturacion" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Inicio_Vigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Fin_Vigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Fecha_Ultimo_Pago" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="DiasTranscurridos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dias_Transcurridos_Pago" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Valor_Poliza" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Total_Pagado" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TotalDescuento" Type="System.Decimal" DbType="Decimal(38,2) NOT NULL" CanBeNull="false" />
      <Column Name="Balance_Pendiente" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Ramo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubRamo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreRamo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NombreSubRamo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Inicial" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Inicial_Pagado" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Cuota" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="C1_Pagada" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="C1" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="C2_Pagada" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="C2" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="C3_Pagada" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="C3" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="C4_Pagada" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="C4" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="C5_Pagada" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="C5" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_REPORTE_ANTIGUEDAD_POR_ATRASO_RESULTADO" Method="SP_REPORTE_ANTIGUEDAD_POR_ATRASO_RESULTADO">
    <Parameter Name="Supervisor" Parameter="supervisor" Type="System.Int32" DbType="Int" />
    <Parameter Name="Intermediario" Parameter="intermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUaurio" Parameter="idUaurio" Type="System.Decimal" DbType="Decimal(20,2)" />
    <ElementType Name="SP_REPORTE_ANTIGUEDAD_POR_ATRASO_RESULTADOResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fecha_Facturacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Inicio_Vigencia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fin_Vigencia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fecha_Ultimo_Pago" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(233) NOT NULL" CanBeNull="false" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(233) NOT NULL" CanBeNull="false" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(233) NOT NULL" CanBeNull="false" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Valor_Poliza" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total_Pagado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Balance_Pendiente" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Ramo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreRamo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SubRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreSubRamo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Balance_En_Atraso" Type="System.Decimal" DbType="Decimal(26,2)" CanBeNull="true" />
      <Column Name="Inicial" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cuota" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Pago_0_10" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Pago_0_30" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Pago_31_60" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Pago_61_90" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Pago_91_120" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Pago_121_Mas" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="DiasTranscurridos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Atraso_0_30" Type="System.Decimal" DbType="Decimal(22,2) NOT NULL" CanBeNull="false" />
      <Column Name="Atraso_31_60" Type="System.Decimal" DbType="Decimal(22,2) NOT NULL" CanBeNull="false" />
      <Column Name="Atraso_61_90" Type="System.Decimal" DbType="Decimal(23,2) NOT NULL" CanBeNull="false" />
      <Column Name="Atraso_91_120" Type="System.Decimal" DbType="Decimal(22,2) NOT NULL" CanBeNull="false" />
      <Column Name="Atraso_Mas_120_Dias" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>