#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilidadesAmigos.Data.Conexiones.LINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SysFlexSeguros")]
	public partial class BDConexionTransitoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BDConexionTransitoDataContext() : 
				base(global::UtilidadesAmigos.Data.Properties.Settings.Default.SysFlexSegurosConnectionString6, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionTransitoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionTransitoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionTransitoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDConexionTransitoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Utililades.SP_GENERAR_MARBETE_VEHICULO_TRANSITO")]
		public ISingleResult<SP_GENERAR_MARBETE_VEHICULO_TRANSITOResult> SP_GENERAR_MARBETE_VEHICULO_TRANSITO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Poliza", DbType="VarChar(50)")] string poliza, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Item", DbType="Int")] System.Nullable<int> item, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaProcesoDesde", DbType="Date")] System.Nullable<System.DateTime> fechaProcesoDesde, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaProcesoHasta", DbType="Date")] System.Nullable<System.DateTime> fechaProcesoHasta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Supervisor", DbType="Int")] System.Nullable<int> supervisor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Intermediario", DbType="Int")] System.Nullable<int> intermediario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Oficina", DbType="Int")] System.Nullable<int> oficina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PolizaImpresa", DbType="VarChar(2)")] string polizaImpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(100)")] string usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), poliza, item, fechaProcesoDesde, fechaProcesoHasta, supervisor, intermediario, oficina, polizaImpresa, usuario);
			return ((ISingleResult<SP_GENERAR_MARBETE_VEHICULO_TRANSITOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Utililades.SP_GENERAR_ENDOSOS_TRANSITO")]
		public ISingleResult<SP_GENERAR_ENDOSOS_TRANSITOResult> SP_GENERAR_ENDOSOS_TRANSITO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Poliza", DbType="VarChar(50)")] string poliza, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Item", DbType="Int")] System.Nullable<int> item, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GeneradoPor", DbType="Int")] System.Nullable<int> generadoPor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndosadoA", DbType="VarChar(1000)")] string endosadoA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ValorCredito", DbType="Decimal(20,2)")] System.Nullable<decimal> valorCredito, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MontoDeducible", DbType="Decimal(20,2)")] System.Nullable<decimal> montoDeducible)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), poliza, item, generadoPor, endosadoA, valorCredito, montoDeducible);
			return ((ISingleResult<SP_GENERAR_ENDOSOS_TRANSITOResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_GENERAR_MARBETE_VEHICULO_TRANSITOResult
	{
		
		private string _Poliza;
		
		private System.Nullable<decimal> _ValorAnual;
		
		private System.Nullable<System.DateTime> _FechaFacturacion;
		
		private string _Fecha;
		
		private string _Hora;
		
		private string _UsuarioAdiciona;
		
		private System.Nullable<int> _Oficina;
		
		private string _NombreOficina;
		
		private string _ConceptoMov;
		
		private string _Cliente;
		
		private int _CodigoIntermediario;
		
		private string _Intermediario;
		
		private int _CodigoSupervisor;
		
		private string _Supervisor;
		
		private string _TipoVehiculo;
		
		private string _Marca;
		
		private string _Modelo;
		
		private string _Chasis;
		
		private string _Placa;
		
		private int _NumeroItem;
		
		private string _Color;
		
		private string _Uso;
		
		private string _Ano;
		
		private string _Asegurado;
		
		private string _FianzaJudicial;
		
		private string _InicioVigencia;
		
		private string _FinVigencia;
		
		private string _Grua;
		
		private string _TelefonoGrua;
		
		private string _InformacionGrua;
		
		private string _Servicios;
		
		private string _TelefonoServicios;
		
		private string _InformacionServicios;
		
		private string _Impresa;
		
		private int _CantidadImpresiones;
		
		public SP_GENERAR_MARBETE_VEHICULO_TRANSITOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Poliza", DbType="VarChar(50)")]
		public string Poliza
		{
			get
			{
				return this._Poliza;
			}
			set
			{
				if ((this._Poliza != value))
				{
					this._Poliza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorAnual", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ValorAnual
		{
			get
			{
				return this._ValorAnual;
			}
			set
			{
				if ((this._ValorAnual != value))
				{
					this._ValorAnual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFacturacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaFacturacion
		{
			get
			{
				return this._FechaFacturacion;
			}
			set
			{
				if ((this._FechaFacturacion != value))
				{
					this._FechaFacturacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="NVarChar(4000)")]
		public string Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora", DbType="NVarChar(4000)")]
		public string Hora
		{
			get
			{
				return this._Hora;
			}
			set
			{
				if ((this._Hora != value))
				{
					this._Hora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="NVarChar(50)")]
		public string UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oficina", DbType="Int")]
		public System.Nullable<int> Oficina
		{
			get
			{
				return this._Oficina;
			}
			set
			{
				if ((this._Oficina != value))
				{
					this._Oficina = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreOficina", DbType="VarChar(100)")]
		public string NombreOficina
		{
			get
			{
				return this._NombreOficina;
			}
			set
			{
				if ((this._NombreOficina != value))
				{
					this._NombreOficina = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConceptoMov", DbType="VarChar(50)")]
		public string ConceptoMov
		{
			get
			{
				return this._ConceptoMov;
			}
			set
			{
				if ((this._ConceptoMov != value))
				{
					this._ConceptoMov = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="VarChar(255)")]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this._Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoIntermediario", DbType="Int NOT NULL")]
		public int CodigoIntermediario
		{
			get
			{
				return this._CodigoIntermediario;
			}
			set
			{
				if ((this._CodigoIntermediario != value))
				{
					this._CodigoIntermediario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Intermediario", DbType="VarChar(200)")]
		public string Intermediario
		{
			get
			{
				return this._Intermediario;
			}
			set
			{
				if ((this._Intermediario != value))
				{
					this._Intermediario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoSupervisor", DbType="Int NOT NULL")]
		public int CodigoSupervisor
		{
			get
			{
				return this._CodigoSupervisor;
			}
			set
			{
				if ((this._CodigoSupervisor != value))
				{
					this._CodigoSupervisor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supervisor", DbType="VarChar(200)")]
		public string Supervisor
		{
			get
			{
				return this._Supervisor;
			}
			set
			{
				if ((this._Supervisor != value))
				{
					this._Supervisor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoVehiculo", DbType="VarChar(200)")]
		public string TipoVehiculo
		{
			get
			{
				return this._TipoVehiculo;
			}
			set
			{
				if ((this._TipoVehiculo != value))
				{
					this._TipoVehiculo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="VarChar(200)")]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this._Marca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modelo", DbType="VarChar(200)")]
		public string Modelo
		{
			get
			{
				return this._Modelo;
			}
			set
			{
				if ((this._Modelo != value))
				{
					this._Modelo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chasis", DbType="VarChar(200)")]
		public string Chasis
		{
			get
			{
				return this._Chasis;
			}
			set
			{
				if ((this._Chasis != value))
				{
					this._Chasis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Placa", DbType="VarChar(200)")]
		public string Placa
		{
			get
			{
				return this._Placa;
			}
			set
			{
				if ((this._Placa != value))
				{
					this._Placa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroItem", DbType="Int NOT NULL")]
		public int NumeroItem
		{
			get
			{
				return this._NumeroItem;
			}
			set
			{
				if ((this._NumeroItem != value))
				{
					this._NumeroItem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(200)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uso", DbType="VarChar(200)")]
		public string Uso
		{
			get
			{
				return this._Uso;
			}
			set
			{
				if ((this._Uso != value))
				{
					this._Uso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ano", DbType="VarChar(200)")]
		public string Ano
		{
			get
			{
				return this._Ano;
			}
			set
			{
				if ((this._Ano != value))
				{
					this._Ano = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asegurado", DbType="VarChar(200)")]
		public string Asegurado
		{
			get
			{
				return this._Asegurado;
			}
			set
			{
				if ((this._Asegurado != value))
				{
					this._Asegurado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FianzaJudicial", DbType="VarChar(200)")]
		public string FianzaJudicial
		{
			get
			{
				return this._FianzaJudicial;
			}
			set
			{
				if ((this._FianzaJudicial != value))
				{
					this._FianzaJudicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InicioVigencia", DbType="NVarChar(4000)")]
		public string InicioVigencia
		{
			get
			{
				return this._InicioVigencia;
			}
			set
			{
				if ((this._InicioVigencia != value))
				{
					this._InicioVigencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinVigencia", DbType="NVarChar(4000)")]
		public string FinVigencia
		{
			get
			{
				return this._FinVigencia;
			}
			set
			{
				if ((this._FinVigencia != value))
				{
					this._FinVigencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grua", DbType="VarChar(250)")]
		public string Grua
		{
			get
			{
				return this._Grua;
			}
			set
			{
				if ((this._Grua != value))
				{
					this._Grua = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoGrua", DbType="VarChar(14) NOT NULL", CanBeNull=false)]
		public string TelefonoGrua
		{
			get
			{
				return this._TelefonoGrua;
			}
			set
			{
				if ((this._TelefonoGrua != value))
				{
					this._TelefonoGrua = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformacionGrua", DbType="VarChar(266) NOT NULL", CanBeNull=false)]
		public string InformacionGrua
		{
			get
			{
				return this._InformacionGrua;
			}
			set
			{
				if ((this._InformacionGrua != value))
				{
					this._InformacionGrua = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Servicios", DbType="VarChar(250)")]
		public string Servicios
		{
			get
			{
				return this._Servicios;
			}
			set
			{
				if ((this._Servicios != value))
				{
					this._Servicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoServicios", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string TelefonoServicios
		{
			get
			{
				return this._TelefonoServicios;
			}
			set
			{
				if ((this._TelefonoServicios != value))
				{
					this._TelefonoServicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformacionServicios", DbType="VarChar(253) NOT NULL", CanBeNull=false)]
		public string InformacionServicios
		{
			get
			{
				return this._InformacionServicios;
			}
			set
			{
				if ((this._InformacionServicios != value))
				{
					this._InformacionServicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impresa", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string Impresa
		{
			get
			{
				return this._Impresa;
			}
			set
			{
				if ((this._Impresa != value))
				{
					this._Impresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadImpresiones", DbType="Int NOT NULL")]
		public int CantidadImpresiones
		{
			get
			{
				return this._CantidadImpresiones;
			}
			set
			{
				if ((this._CantidadImpresiones != value))
				{
					this._CantidadImpresiones = value;
				}
			}
		}
	}
	
	public partial class SP_GENERAR_ENDOSOS_TRANSITOResult
	{
		
		private string _Poliza;
		
		private string _Moneda;
		
		private string _Moneda1;
		
		private System.Nullable<decimal> _ValorAnual;
		
		private System.Nullable<System.DateTime> _FechaFacturacion;
		
		private string _Mes;
		
		private string _Ano;
		
		private string _Fecha;
		
		private string _Hora;
		
		private string _UsuarioAdiciona;
		
		private System.Nullable<int> _Oficina;
		
		private string _NombreOficina;
		
		private string _ConceptoMov;
		
		private string _Cliente;
		
		private string _Direccion;
		
		private int _CodigoIntermediario;
		
		private string _Intermediario;
		
		private int _CodigoSupervisor;
		
		private string _Supervisor;
		
		private string _TipoVehiculo;
		
		private string _Marca;
		
		private string _Modelo;
		
		private string _Chasis;
		
		private string _Placa;
		
		private int _NumeroItem;
		
		private string _Color;
		
		private string _Uso;
		
		private string _Ano1;
		
		private string _Asegurado;
		
		private string _FianzaJudicial;
		
		private System.Nullable<decimal> _ValorVehiculo;
		
		private string _InicioVigencia;
		
		private string _FinVigencia;
		
		private string _Grua;
		
		private string _Servicios;
		
		private int _CodigoRamo;
		
		private string _Ramo;
		
		private int _CodigoSubRamo;
		
		private string _SubRamo;
		
		private string _GeneradoPor;
		
		private string _EndosadoA;
		
		private System.Nullable<decimal> _ValorCredito;
		
		private System.Nullable<decimal> _MontoDeducible;
		
		private string _ColisionVuelco;
		
		private string _RiesgoComprensivo;
		
		private string _Incendio;
		
		private string _Robo;
		
		public SP_GENERAR_ENDOSOS_TRANSITOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Poliza", DbType="VarChar(50)")]
		public string Poliza
		{
			get
			{
				return this._Poliza;
			}
			set
			{
				if ((this._Poliza != value))
				{
					this._Poliza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Moneda", DbType="VarChar(50)")]
		public string Moneda
		{
			get
			{
				return this._Moneda;
			}
			set
			{
				if ((this._Moneda != value))
				{
					this._Moneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Moneda1", DbType="VarChar(10)")]
		public string Moneda1
		{
			get
			{
				return this._Moneda1;
			}
			set
			{
				if ((this._Moneda1 != value))
				{
					this._Moneda1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorAnual", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ValorAnual
		{
			get
			{
				return this._ValorAnual;
			}
			set
			{
				if ((this._ValorAnual != value))
				{
					this._ValorAnual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFacturacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaFacturacion
		{
			get
			{
				return this._FechaFacturacion;
			}
			set
			{
				if ((this._FechaFacturacion != value))
				{
					this._FechaFacturacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mes", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Mes
		{
			get
			{
				return this._Mes;
			}
			set
			{
				if ((this._Mes != value))
				{
					this._Mes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ano", DbType="VarChar(30)")]
		public string Ano
		{
			get
			{
				return this._Ano;
			}
			set
			{
				if ((this._Ano != value))
				{
					this._Ano = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="NVarChar(4000)")]
		public string Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora", DbType="NVarChar(4000)")]
		public string Hora
		{
			get
			{
				return this._Hora;
			}
			set
			{
				if ((this._Hora != value))
				{
					this._Hora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="NVarChar(50)")]
		public string UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oficina", DbType="Int")]
		public System.Nullable<int> Oficina
		{
			get
			{
				return this._Oficina;
			}
			set
			{
				if ((this._Oficina != value))
				{
					this._Oficina = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreOficina", DbType="VarChar(100)")]
		public string NombreOficina
		{
			get
			{
				return this._NombreOficina;
			}
			set
			{
				if ((this._NombreOficina != value))
				{
					this._NombreOficina = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConceptoMov", DbType="VarChar(50)")]
		public string ConceptoMov
		{
			get
			{
				return this._ConceptoMov;
			}
			set
			{
				if ((this._ConceptoMov != value))
				{
					this._ConceptoMov = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="VarChar(255)")]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this._Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(255)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoIntermediario", DbType="Int NOT NULL")]
		public int CodigoIntermediario
		{
			get
			{
				return this._CodigoIntermediario;
			}
			set
			{
				if ((this._CodigoIntermediario != value))
				{
					this._CodigoIntermediario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Intermediario", DbType="VarChar(200)")]
		public string Intermediario
		{
			get
			{
				return this._Intermediario;
			}
			set
			{
				if ((this._Intermediario != value))
				{
					this._Intermediario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoSupervisor", DbType="Int NOT NULL")]
		public int CodigoSupervisor
		{
			get
			{
				return this._CodigoSupervisor;
			}
			set
			{
				if ((this._CodigoSupervisor != value))
				{
					this._CodigoSupervisor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supervisor", DbType="VarChar(200)")]
		public string Supervisor
		{
			get
			{
				return this._Supervisor;
			}
			set
			{
				if ((this._Supervisor != value))
				{
					this._Supervisor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoVehiculo", DbType="VarChar(200)")]
		public string TipoVehiculo
		{
			get
			{
				return this._TipoVehiculo;
			}
			set
			{
				if ((this._TipoVehiculo != value))
				{
					this._TipoVehiculo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="VarChar(200)")]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this._Marca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modelo", DbType="VarChar(200)")]
		public string Modelo
		{
			get
			{
				return this._Modelo;
			}
			set
			{
				if ((this._Modelo != value))
				{
					this._Modelo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chasis", DbType="VarChar(200)")]
		public string Chasis
		{
			get
			{
				return this._Chasis;
			}
			set
			{
				if ((this._Chasis != value))
				{
					this._Chasis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Placa", DbType="VarChar(200)")]
		public string Placa
		{
			get
			{
				return this._Placa;
			}
			set
			{
				if ((this._Placa != value))
				{
					this._Placa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroItem", DbType="Int NOT NULL")]
		public int NumeroItem
		{
			get
			{
				return this._NumeroItem;
			}
			set
			{
				if ((this._NumeroItem != value))
				{
					this._NumeroItem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(200)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uso", DbType="VarChar(200)")]
		public string Uso
		{
			get
			{
				return this._Uso;
			}
			set
			{
				if ((this._Uso != value))
				{
					this._Uso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ano1", DbType="VarChar(200)")]
		public string Ano1
		{
			get
			{
				return this._Ano1;
			}
			set
			{
				if ((this._Ano1 != value))
				{
					this._Ano1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asegurado", DbType="VarChar(200)")]
		public string Asegurado
		{
			get
			{
				return this._Asegurado;
			}
			set
			{
				if ((this._Asegurado != value))
				{
					this._Asegurado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FianzaJudicial", DbType="VarChar(200)")]
		public string FianzaJudicial
		{
			get
			{
				return this._FianzaJudicial;
			}
			set
			{
				if ((this._FianzaJudicial != value))
				{
					this._FianzaJudicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorVehiculo", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ValorVehiculo
		{
			get
			{
				return this._ValorVehiculo;
			}
			set
			{
				if ((this._ValorVehiculo != value))
				{
					this._ValorVehiculo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InicioVigencia", DbType="NVarChar(4000)")]
		public string InicioVigencia
		{
			get
			{
				return this._InicioVigencia;
			}
			set
			{
				if ((this._InicioVigencia != value))
				{
					this._InicioVigencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinVigencia", DbType="NVarChar(4000)")]
		public string FinVigencia
		{
			get
			{
				return this._FinVigencia;
			}
			set
			{
				if ((this._FinVigencia != value))
				{
					this._FinVigencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grua", DbType="VarChar(250)")]
		public string Grua
		{
			get
			{
				return this._Grua;
			}
			set
			{
				if ((this._Grua != value))
				{
					this._Grua = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Servicios", DbType="VarChar(250)")]
		public string Servicios
		{
			get
			{
				return this._Servicios;
			}
			set
			{
				if ((this._Servicios != value))
				{
					this._Servicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoRamo", DbType="Int NOT NULL")]
		public int CodigoRamo
		{
			get
			{
				return this._CodigoRamo;
			}
			set
			{
				if ((this._CodigoRamo != value))
				{
					this._CodigoRamo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ramo", DbType="NVarChar(50)")]
		public string Ramo
		{
			get
			{
				return this._Ramo;
			}
			set
			{
				if ((this._Ramo != value))
				{
					this._Ramo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoSubRamo", DbType="Int NOT NULL")]
		public int CodigoSubRamo
		{
			get
			{
				return this._CodigoSubRamo;
			}
			set
			{
				if ((this._CodigoSubRamo != value))
				{
					this._CodigoSubRamo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubRamo", DbType="NVarChar(50)")]
		public string SubRamo
		{
			get
			{
				return this._SubRamo;
			}
			set
			{
				if ((this._SubRamo != value))
				{
					this._SubRamo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeneradoPor", DbType="VarChar(150)")]
		public string GeneradoPor
		{
			get
			{
				return this._GeneradoPor;
			}
			set
			{
				if ((this._GeneradoPor != value))
				{
					this._GeneradoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndosadoA", DbType="VarChar(1000)")]
		public string EndosadoA
		{
			get
			{
				return this._EndosadoA;
			}
			set
			{
				if ((this._EndosadoA != value))
				{
					this._EndosadoA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorCredito", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ValorCredito
		{
			get
			{
				return this._ValorCredito;
			}
			set
			{
				if ((this._ValorCredito != value))
				{
					this._ValorCredito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoDeducible", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoDeducible
		{
			get
			{
				return this._MontoDeducible;
			}
			set
			{
				if ((this._MontoDeducible != value))
				{
					this._MontoDeducible = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColisionVuelco", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string ColisionVuelco
		{
			get
			{
				return this._ColisionVuelco;
			}
			set
			{
				if ((this._ColisionVuelco != value))
				{
					this._ColisionVuelco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RiesgoComprensivo", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string RiesgoComprensivo
		{
			get
			{
				return this._RiesgoComprensivo;
			}
			set
			{
				if ((this._RiesgoComprensivo != value))
				{
					this._RiesgoComprensivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Incendio", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Incendio
		{
			get
			{
				return this._Incendio;
			}
			set
			{
				if ((this._Incendio != value))
				{
					this._Incendio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Robo", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Robo
		{
			get
			{
				return this._Robo;
			}
			set
			{
				if ((this._Robo != value))
				{
					this._Robo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
