<?xml version="1.0" encoding="utf-8"?><Database Name="SysFlexSeguros" Class="BDConexionProcesosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.25.24.3;Initial Catalog=SysFlexSeguros;Integrated Security=False;User ID=sa" SettingsObjectName="UtilidadesAmigos.Data.Properties.Settings" SettingsPropertyName="SysFlexSegurosConnectionString2" Provider="System.Data.SqlClient" />
  <Function Name="Utililades.SP_GENERAR_DATOS_PARA_MARBETE_VEHICULO" Method="SP_GENERAR_DATOS_PARA_MARBETE_VEHICULO">
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Item" Parameter="item" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Chasis" Parameter="chasis" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Placa" Parameter="placa" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SP_GENERAR_DATOS_PARA_MARBETE_VEHICULOResult">
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoCliente" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreCliente" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Asegurado" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TipoVehiculo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Modelo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Chasis" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Placa" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Uso" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Ano" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Capacidad" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ValorVehiculo" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="FianzaJudicial" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Vendedor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Grua" Type="System.String" DbType="VarChar(269) NOT NULL" CanBeNull="false" />
      <Column Name="AeroAmbulancia" Type="System.String" DbType="VarChar(269) NOT NULL" CanBeNull="false" />
      <Column Name="OtrosServicios" Type="System.String" DbType="VarChar(251) NOT NULL" CanBeNull="false" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_MARBETES" Method="SP_PROCESAR_INFORMACION_MARBETES">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Cotizacion" Parameter="cotizacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoCliente" Parameter="codigoCliente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="NombreCliente" Parameter="nombreCliente" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="InicioVigencia" Parameter="inicioVigencia" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="FinVigencia" Parameter="finVigencia" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Asegurado" Parameter="asegurado" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="TipoVehiculo" Parameter="tipoVehiculo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Marca" Parameter="marca" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Modelo" Parameter="modelo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Chasis" Parameter="chasis" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Placa" Parameter="placa" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Color" Parameter="color" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Uso" Parameter="uso" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Ano" Parameter="ano" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Capacidad" Parameter="capacidad" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ValorVehiculo" Parameter="valorVehiculo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="FianzaJudicial" Parameter="fianzaJudicial" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Vendedor" Parameter="vendedor" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Grua" Parameter="grua" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="AeroAmbulancia" Parameter="aeroAmbulancia" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="OtrosServicios" Parameter="otrosServicios" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="CantidadRegistros" Parameter="cantidadRegistros" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_MARBETESResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoCliente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreCliente" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Asegurado" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TipoVehiculo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Modelo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Chasis" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Placa" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Uso" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Ano" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Capacidad" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorVehiculo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="FianzaJudicial" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Vendedor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Grua" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="AeroAmbulancia" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="OtrosServicios" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_HISTORICO_IMPRESION_MARBETE" Method="SP_PROCESAR_HISTORICO_IMPRESION_MARBETE">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(25,0)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Cotizacion" Parameter="cotizacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoCliente" Parameter="codigoCliente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="NombreCliente" Parameter="nombreCliente" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="InicioVigencia" Parameter="inicioVigencia" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="FinVigencia" Parameter="finVigencia" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Asegurado" Parameter="asegurado" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="TipoVehiculo" Parameter="tipoVehiculo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="MarcaVehiculo" Parameter="marcaVehiculo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ModeloVehiculo" Parameter="modeloVehiculo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Chasis" Parameter="chasis" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Placa" Parameter="placa" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Color" Parameter="color" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="uso" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Ano" Parameter="ano" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Capacidad" Parameter="capacidad" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ValorVehiculo" Parameter="valorVehiculo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="FianzaJudicial" Parameter="fianzaJudicial" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Vendedor" Parameter="vendedor" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Grua" Parameter="grua" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="AeroAmbulancia" Parameter="aeroAmbulancia" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="OtrosServicios" Parameter="otrosServicios" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="UsuarioImprime" Parameter="usuarioImprime" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoImpresion" Parameter="tipoImpresion" Type="System.Int32" DbType="Int" />
    <Parameter Name="CantidadImpreso" Parameter="cantidadImpreso" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_HISTORICO_IMPRESION_MARBETEResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(25,0)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoCliente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreCliente" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Asegurado" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TipoVehiculo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MarcaVehiculo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ModeloVehiculo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Chasis" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Placa" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="uso" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Ano" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Capacidad" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorVehiculo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="FianzaJudicial" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Vendedor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Grua" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="AeroAmbulancia" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="OtrosServicios" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioImprime" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoImpresion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadImpreso" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_HISTORICO_IMPRESION_MARBETES" Method="SP_BUSCA_HISTORICO_IMPRESION_MARBETES">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(25,0)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ITEM" Parameter="iTEM" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="InicioVigencia" Parameter="inicioVigencia" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FinVigencia" Parameter="finVigencia" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Cotizacion" Parameter="cotizacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NombreCliente" Parameter="nombreCliente" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="Asegurado" Parameter="asegurado" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="TipoVehiculo" Parameter="tipoVehiculo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="MarcaVehiculo" Parameter="marcaVehiculo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ModeloVehiculo" Parameter="modeloVehiculo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Chasis" Parameter="chasis" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Placa" Parameter="placa" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Ano" Parameter="ano" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Vendedor" Parameter="vendedor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoImpresion" Parameter="tipoImpresion" Type="System.Int32" DbType="Int" />
    <Parameter Name="NombreUsuario" Parameter="nombreUsuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaImpresionDesde" Parameter="fechaImpresionDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaImpresionHasta" Parameter="fechaImpresionHasta" Type="System.DateTime" DbType="Date" />
    <ElementType Name="SP_BUSCA_HISTORICO_IMPRESION_MARBETESResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(25,0) NOT NULL" CanBeNull="false" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoCliente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreCliente" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Asegurado" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TipoVehiculo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MarcaVehiculo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ModeloVehiculo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Chasis" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Placa" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="uso" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Ano" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Capacidad" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorVehiculo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="FianzaJudicial" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Vendedor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Grua" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="AeroAmbulancia" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="OtrosServicios" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaCreado0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioImprime" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoImpresion0" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoImpresion" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="CantidadImpreso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CandidadImpresionesPVC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CandidadImpresionesHoja" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CandidadImpresiones" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CandidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_HISTORICO_IMPRESION_MARBETE_RESUMIDO" Method="SP_BUSCA_HISTORICO_IMPRESION_MARBETE_RESUMIDO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_HISTORICO_IMPRESION_MARBETE_RESUMIDOResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="UsuarioImprime" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoImprecion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CantidadImpresion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadPVC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadHoja" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalImpresiones" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadMovimientos" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MANTENIMIENTO_HISTORICO_IMPRESION_MARBETE_RESUMIDO" Method="SP_MANTENIMIENTO_HISTORICO_IMPRESION_MARBETE_RESUMIDO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(25,0)" />
    <Parameter Name="UsuarioImprime" Parameter="usuarioImprime" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoImprecion" Parameter="tipoImprecion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CantidadImpresion" Parameter="cantidadImpresion" Type="System.Int32" DbType="Int" />
    <Parameter Name="CantidadPVC" Parameter="cantidadPVC" Type="System.Int32" DbType="Int" />
    <Parameter Name="CantidadHoja" Parameter="cantidadHoja" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalImpresiones" Parameter="totalImpresiones" Type="System.Int32" DbType="Int" />
    <Parameter Name="CantidadMovimientos" Parameter="cantidadMovimientos" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_HISTORICO_IMPRESION_MARBETE_RESUMIDOResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(25,0)" CanBeNull="true" />
      <Column Name="UsuarioImprime" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoImprecion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CantidadImpresion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadPVC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadHoja" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalImpresiones" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadMovimientos" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_INFORMACION_CORREOS_EMISORES_SISTEMA" Method="SP_BUSCA_INFORMACION_CORREOS_EMISORES_SISTEMA">
    <Parameter Name="IdCorreo" Parameter="idCorreo" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdProceso" Parameter="idProceso" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_INFORMACION_CORREOS_EMISORES_SISTEMAResult">
      <Column Name="IdCorreo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdProceso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Proceso" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Puerto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SMTP" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MODIFICAR_CORREOS_EMISORES_SISTEMA" Method="SP_MODIFICAR_CORREOS_EMISORES_SISTEMA">
    <Parameter Name="IdCorreo" Parameter="idCorreo" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdProceso" Parameter="idProceso" Type="System.Int32" DbType="Int" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Clave" Parameter="clave" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Puerto" Parameter="puerto" Type="System.Int32" DbType="Int" />
    <Parameter Name="SMTP" Parameter="sMTP" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MODIFICAR_CORREOS_EMISORES_SISTEMAResult">
      <Column Name="IdCorreo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdProceso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Puerto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SMTP" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCAR_INFORMACION_VOLANTES_PAGOS" Method="SP_BUSCAR_INFORMACION_VOLANTES_PAGOS">
    <Parameter Name="CodigoEmpleado" Parameter="codigoEmpleado" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ano" Parameter="ano" Type="System.Int32" DbType="Int" />
    <Parameter Name="Mes" Parameter="mes" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="TipoMovimiento" Parameter="tipoMovimiento" Type="System.Int32" DbType="Int" />
    <Parameter Name="TipoNomina" Parameter="tipoNomina" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="NoPago" Parameter="noPago" Type="System.Int32" DbType="Int" />
    <Parameter Name="CodigoSucursal" Parameter="codigoSucursal" Type="System.Int32" DbType="Int" />
    <Parameter Name="CodigoDepartamento" Parameter="codigoDepartamento" Type="System.Int32" DbType="Int" />
    <Parameter Name="NombreEmpleado" Parameter="nombreEmpleado" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_BUSCAR_INFORMACION_VOLANTES_PAGOSResult">
      <Column Name="CodEmpleado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ano" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mes" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="NombreMes" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TipoMovimiento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DescTipoMovimiento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TipoNomina" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DescTipoNomina" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NoPago" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sucursal" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DescSucursal" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Departamento" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DescDepto" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NombreEmpleado" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="Origen" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="Valor" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Ingresos" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Deducciones" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TotalIngreso" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalDeducciones" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_EMPLEADOS" Method="SP_BUSCA_EMPLEADOS">
    <Parameter Name="CodigoEmpleado" Parameter="codigoEmpleado" Type="System.Int32" DbType="Int" />
    <Parameter Name="NombreEmpleado" Parameter="nombreEmpleado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Sucursar" Parameter="sucursar" Type="System.Int32" DbType="Int" />
    <Parameter Name="Departamento" Parameter="departamento" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cargo" Parameter="cargo" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaIngresoDesde" Parameter="fechaIngresoDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaIngresoHasta" Parameter="fechaIngresoHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="SP_BUSCA_EMPLEADOSResult">
      <Column Name="CodigoEmpleado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="Sucursal" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DescSucursal" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Departamento" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DescDepto" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Cargo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescCargo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cedula" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FechaIngreso0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaIngreso" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_SACAR_RUTA_ARCHIVO_GUARDADO" Method="SP_SACAR_RUTA_ARCHIVO_GUARDADO">
    <Parameter Name="IdArchivo" Parameter="idArchivo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_SACAR_RUTA_ARCHIVO_GUARDADOResult">
      <Column Name="IdRutaGuardado" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Ruta" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_SACAR_CREDENCIALES_BD" Method="SP_SACAR_CREDENCIALES_BD">
    <Parameter Name="IdCredencial" Parameter="idCredencial" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_SACAR_CREDENCIALES_BDResult">
      <Column Name="IdCredencial" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MODIFICAR_REDENCIALES_BD" Method="SP_MODIFICAR_REDENCIALES_BD">
    <Parameter Name="IdCredencial" Parameter="idCredencial" Type="System.Int32" DbType="Int" />
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Clave" Parameter="clave" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MODIFICAR_REDENCIALES_BDResult">
      <Column Name="IdCredencial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_VALIDAR_CODIGO_EMPLEADO_VOLANTE_PAGO" Method="SP_VALIDAR_CODIGO_EMPLEADO_VOLANTE_PAGO">
    <Parameter Name="CodigoEmpleado" Parameter="codigoEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_VALIDAR_CODIGO_EMPLEADO_VOLANTE_PAGOResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EnvioCorreo0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EnvioCorreo" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MODIFICAR_CODIGOS_EMPLEADOS_VOLANTE_PAGOS" Method="SP_MODIFICAR_CODIGOS_EMPLEADOS_VOLANTE_PAGOS">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoEmpleado" Parameter="codigoEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="EnvioCorreo" Parameter="envioCorreo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MODIFICAR_CODIGOS_EMPLEADOS_VOLANTE_PAGOSResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoEmpleado" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EnvioCorreo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_FORMA_PAGO_COBROS" Method="SP_BUSCA_FORMA_PAGO_COBROS">
    <Parameter Name="NumeroRecibo" Parameter="numeroRecibo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_FORMA_PAGO_COBROSResult">
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Numero_Recibo" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_pago" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MODIFICAR_FORMA_PAGO_RECIBO" Method="SP_MODIFICAR_FORMA_PAGO_RECIBO">
    <Parameter Name="Numero_Recibo" Parameter="numero_Recibo" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MODIFICAR_FORMA_PAGO_RECIBOResult">
      <Column Name="Compania" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoFactura" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Anulado" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="sistema" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tipo_documento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Numero_Recibo" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Fecha_pago" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="No_Documento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="No_Aprobacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fecha_Vencimiento" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Cod_Banco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tipo_Tarjeta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_DATO_RECLAMACION_AGREGAR_ITEMS" Method="SP_BUSCA_DATO_RECLAMACION_AGREGAR_ITEMS">
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NumeroReclamo" Parameter="numeroReclamo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_DATO_RECLAMACION_AGREGAR_ITEMSResult">
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Reclamacion" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoReclamacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TipoReclamacion" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="IdReclamante" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Reclamante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCAR_NOMBRE_RECLAMANTE" Method="SP_BUSCAR_NOMBRE_RECLAMANTE">
    <Parameter Name="CodigoReclamante" Parameter="codigoReclamante" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCAR_NOMBRE_RECLAMANTEResult">
      <Column Name="Codigo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreReclamante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_AGREGAR_EDITAR_ELIMINAR_ITEMS_RECLAMACIONES" Method="SP_AGREGAR_EDITAR_ELIMINAR_ITEMS_RECLAMACIONES">
    <Parameter Name="Reclamacion" Parameter="reclamacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdReclamante" Parameter="idReclamante" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdTipoReclamacion" Parameter="idTipoReclamacion" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_AGREGAR_EDITAR_ELIMINAR_ITEMS_RECLAMACIONESResult">
      <Column Name="Compania" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Reclamacion" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdTipoReclamacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdReclamante" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MontoReclamado" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MontoAjustado" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MontoReserva" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MontoDeducible" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdEjecutivoReclamacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_RECIBO_DIGITAL" Method="SP_PROCESAR_RECIBO_DIGITAL">
    <Parameter Name="NumeroRecibo" Parameter="numeroRecibo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoIntermediario" Parameter="codigoIntermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ValorRecibo" Parameter="valorRecibo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Int32" DbType="Int" />
    <Parameter Name="Detalle" Parameter="detalle" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="CreadoPor" Parameter="creadoPor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Oficina" Parameter="oficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_RECIBO_DIGITALResult">
      <Column Name="NumeroRecibo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaRecibo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ValorRecibo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Detalle" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Oficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_INFORMACION_RECIBO_DIGITAL" Method="SP_BUSCA_INFORMACION_RECIBO_DIGITAL">
    <Parameter Name="NumeroRecibo" Parameter="numeroRecibo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoIntermediario" Parameter="codigoIntermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="CodigoSupervisor" Parameter="codigoSupervisor" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Int32" DbType="Int" />
    <Parameter Name="Oficina" Parameter="oficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="GeneradoPor" Parameter="generadoPor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_INFORMACION_RECIBO_DIGITALResult">
      <Column Name="NumeroRecibo" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(233) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoSupervisor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreIntermediario" Type="System.String" DbType="VarChar(233) NOT NULL" CanBeNull="false" />
      <Column Name="FechaRecibo0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ValorRecibo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ValorReciboLetra" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Detalle" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="CreadoPor0" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IdOficina" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GeneradoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="TotalEfectivo" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalTransferencia" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalDeposito" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalCheque" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalOtro" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_INFORMACION_POLIZA_ENDOSOS" Method="SP_BUSCA_INFORMACION_POLIZA_ENDOSOS">
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Item" Parameter="item" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_INFORMACION_POLIZA_ENDOSOSResult">
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Item" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SubRamo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreRamo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NombreSubRamo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TipoSeguro" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(233) NOT NULL" CanBeNull="false" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(233) NOT NULL" CanBeNull="false" />
      <Column Name="NombreCliente" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TelefonoResidencia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TelefonoOficina" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Modelo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Chasis" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Placa" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Ano" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Grua" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="CodigoGrua" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_ENDOSOS" Method="SP_PROCESAR_INFORMACION_ENDOSOS">
    <Parameter Name="NumeroRegistro" Parameter="numeroRegistro" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="Item" Parameter="item" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cliente" Parameter="cliente" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoRnc" Parameter="tipoRnc" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRnc" Parameter="numeroRnc" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="TelefonoResidencia" Parameter="telefonoResidencia" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="TelefonoOficina" Parameter="telefonoOficina" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Celular" Parameter="celular" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="fax" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="InicioVigencia" Parameter="inicioVigencia" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="FinVigencia" Parameter="finVigencia" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Marca" Parameter="marca" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Modelo" Parameter="modelo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Chasis" Parameter="chasis" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Placa" Parameter="placa" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Color" Parameter="color" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TipoEndoso" Parameter="tipoEndoso" Type="System.Int32" DbType="Int" />
    <Parameter Name="LicenciaExtrajero" Parameter="licenciaExtrajero" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NombreConductorUnico" Parameter="nombreConductorUnico" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CedulaConductorUnico" Parameter="cedulaConductorUnico" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoGrua" Parameter="tipoGrua" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_ENDOSOSResult">
      <Column Name="NumeroRegistro" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Item" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoRnc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumeroRnc" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="TelefonoResidencia" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TelefonoOficina" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Modelo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Chasis" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Placa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TipoEndoso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LicenciaExtrajero" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NombreConductorUnico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CedulaConductorUnico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoGrua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_INFORMACION_ENDOSOS" Method="SP_BUSCA_INFORMACION_ENDOSOS">
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Item" Parameter="item" Type="System.Int32" DbType="Int" />
    <Parameter Name="GeneradoPor" Parameter="generadoPor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoTipoEndoso" Parameter="codigoTipoEndoso" Type="System.Int32" DbType="Int" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="TipoEndoso" Parameter="tipoEndoso" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_INFORMACION_ENDOSOSResult">
      <Column Name="NumeroRegistro" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Item" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoRnc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NumeroRnc" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="TelefonoResidencia" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TelefonoOficina" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Modelo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Chasis" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Placa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodigoTipoEndoso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoEndoso" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LicenciaExtrajero" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NombreConductorUnico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CedulaConductorUnico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoTipoGrua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecuenciaGrua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodigoGruaSistema" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescripcionGrua" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PlanGrua" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TipoAsistenciaPunto" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TipoAsistenciaSubPunto" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="LimiteEventos" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="LimiteCobertura" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PrimaNeta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PrimaBruta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Fecha0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DiaNumerico" Type="System.String" DbType="VarChar(31)" CanBeNull="true" />
      <Column Name="DiaLetra" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Mes" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Ano" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="AnoLetra" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="GeneradoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="EndosadoA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CantidadEndosoAclaratorio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadEndosoLicenciaExtranjero" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadEndosoConductorUnico" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadEndosoAuxilioVial" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>