<?xml version="1.0" encoding="utf-8"?><Database Name="SysFlexSeguros" Class="BDConexionCorreccionesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.25.24.3;Initial Catalog=SysFlexSeguros;Integrated Security=False;User ID=sa" SettingsObjectName="UtilidadesAmigos.Data.Properties.Settings" SettingsPropertyName="SysFlexSegurosConnectionString2" Provider="System.Data.SqlClient" />
  <Function Name="Utililades.SP_BUSCA_ENDOSO_SESION" Method="SP_BUSCA_ENDOSO_SESION">
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Item" Parameter="item" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_ENDOSO_SESIONResult">
      <Column Name="Compania" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodigoRamo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ramo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CodigoSubramo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subramo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FechaInicioVigencia0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaInicioVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FechaFinVigencia0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaFinVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Item" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdBeneficiario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreBeneficiario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ValorEndosoCesion" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_ENDOSOS_POLIZAS" Method="SP_PROCESAR_INFORMACION_ENDOSOS_POLIZAS">
    <Parameter Name="Compania" Parameter="compania" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="Cotizacion" Parameter="cotizacion" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdBeneficiario" Parameter="idBeneficiario" Type="System.Int32" DbType="Int" />
    <Parameter Name="NombreBeneficiario" Parameter="nombreBeneficiario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ValorEndosoCesion" Parameter="valorEndosoCesion" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="UsuarioAdiciona" Parameter="usuarioAdiciona" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FechaAdiciona" Parameter="fechaAdiciona" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_ENDOSOS_POLIZASResult">
      <Column Name="Compania" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdBeneficiario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreBeneficiario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ValorEndosoCesion" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_HISTORICO_ENDOSOS" Method="SP_PROCESAR_INFORMACION_HISTORICO_ENDOSOS">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(31,0)" />
    <Parameter Name="Compania" Parameter="compania" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="Cotizacion" Parameter="cotizacion" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdBeneficiario" Parameter="idBeneficiario" Type="System.Int32" DbType="Int" />
    <Parameter Name="NombreBeneficiario" Parameter="nombreBeneficiario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ValorEndosoCesion" Parameter="valorEndosoCesion" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="UsuarioAdiciona" Parameter="usuarioAdiciona" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FechaAdiciona" Parameter="fechaAdiciona" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UsuarioElimina" Parameter="usuarioElimina" Type="System.Decimal" DbType="Decimal(31,0)" />
    <Parameter Name="FechaProcesoElimina" Parameter="fechaProcesoElimina" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_HISTORICO_ENDOSOSResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(31,0)" CanBeNull="true" />
      <Column Name="Compania" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdBeneficiario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreBeneficiario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorEndosoCesion" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioElimina" Type="System.Decimal" DbType="Decimal(31,0)" CanBeNull="true" />
      <Column Name="FechaProcesoElimina" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCAR_INFORMACION_ENDOSOS_ELIMINADOS" Method="SP_BUSCAR_INFORMACION_ENDOSOS_ELIMINADOS">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(31,0)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaBorradoDesde" Parameter="fechaBorradoDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaBorradoHasta" Parameter="fechaBorradoHasta" Type="System.DateTime" DbType="Date" />
    <ElementType Name="SP_BUSCAR_INFORMACION_ENDOSOS_ELIMINADOSResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(31,0) NOT NULL" CanBeNull="false" />
      <Column Name="Compania" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdBeneficiario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreBeneficiario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorEndosoCesion" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioElimina" Type="System.Decimal" DbType="Decimal(31,0)" CanBeNull="true" />
      <Column Name="EliminadoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FechaProcesoElimina0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaProcesoElimina" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="HoraProcesoElimina" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_BITACORA_MONTO_AFIANZADO" Method="SP_BUSCA_BITACORA_MONTO_AFIANZADO">
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <ElementType Name="SP_BUSCA_BITACORA_MONTO_AFIANZADOResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(31,0) NOT NULL" CanBeNull="false" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Anterior" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cambio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Fecha0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_BITACORA_MONTO_AFIANZADO" Method="SP_PROCESAR_INFORMACION_BITACORA_MONTO_AFIANZADO">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(31,0)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Anterior" Parameter="anterior" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Cambio" Parameter="cambio" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Usuario" Parameter="usuario" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_BITACORA_MONTO_AFIANZADOResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(31,0)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Anterior" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cambio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_INFORMACION_POLIZAS_FIANZAS" Method="SP_BUSCA_INFORMACION_POLIZAS_FIANZAS">
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_BUSCA_INFORMACION_POLIZAS_FIANZASResult">
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SumaAsegurada" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Prima" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreVendedor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Cliente" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NombreCliente" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Deudor" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Ramo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreRamo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SubRamo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreSubramo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Facturado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MODIFICAR_MONTO_AFIANZADO" Method="SP_MODIFICAR_MONTO_AFIANZADO">
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MontoAfianzado" Parameter="montoAfianzado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_MODIFICAR_MONTO_AFIANZADOResult">
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MontoAfianzado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_INFORMACION_POLIZA_EQUIPOS_ELECTRONICOS" Method="SP_BUSCA_INFORMACION_POLIZA_EQUIPOS_ELECTRONICOS">
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Item" Parameter="item" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_INFORMACION_POLIZA_EQUIPOS_ELECTRONICOSResult">
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Item" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cliente" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NombreCliente" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreIntermediario" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CodigoSupervisor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CantidadEquipos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadEquiposTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>