<?xml version="1.0" encoding="utf-8"?><Database Name="SysFlexSeguros" Class="BDConexionSuministroDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.25.24.3;Initial Catalog=SysFlexSeguros;Integrated Security=False;User ID=sa" SettingsObjectName="UtilidadesAmigos.Data.Properties.Settings" SettingsPropertyName="SysFlexSegurosConnectionString2" Provider="System.Data.SqlClient" />
  <Function Name="Utililades.SP_BUSCA_SUMINISTRO_INVENTARIO" Method="SP_BUSCA_SUMINISTRO_INVENTARIO">
    <Parameter Name="CodigoArticulo" Parameter="codigoArticulo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Articulo" Parameter="articulo" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="IdMedida" Parameter="idMedida" Type="System.Int32" DbType="Int" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="GeneradoPor" Parameter="generadoPor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_SUMINISTRO_INVENTARIOResult">
      <Column Name="CodigoArticulo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Articulo" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdMedida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Medida" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioCrea" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FechaCrea0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="HoraCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="HoraModificado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="GeneradoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_SUMINISTRO_INVENTARIO" Method="SP_PROCESAR_INFORMACION_SUMINISTRO_INVENTARIO">
    <Parameter Name="CodigoArticulo" Parameter="codigoArticulo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Articulo" Parameter="articulo" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="IdMedida" Parameter="idMedida" Type="System.Int32" DbType="Int" />
    <Parameter Name="Stock" Parameter="stock" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_SUMINISTRO_INVENTARIOResult">
      <Column Name="CodigoArticulo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Articulo" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdMedida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UsuarioCrea" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaCrea" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_SUMINISTRO_SOLICITUD_ESPEJO" Method="SP_PROCESAR_INFORMACION_SUMINISTRO_SOLICITUD_ESPEJO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoArticulo" Parameter="codigoArticulo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="IdMedida" Parameter="idMedida" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_SUMINISTRO_SOLICITUD_ESPEJOResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoArticulo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdMedida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_SUMINISTRO_SOLICITUD_ESPEJO" Method="SP_BUSCA_SUMINISTRO_SOLICITUD_ESPEJO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoArticulo" Parameter="codigoArticulo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_SUMINISTRO_SOLICITUD_ESPEJOResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoArticulo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdMedida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Medida" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_SUMINISTRO_INVENTARIO_FINAL" Method="SP_BUSCA_SUMINISTRO_INVENTARIO_FINAL">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(31,0)" />
    <Parameter Name="IdSucursal" Parameter="idSucursal" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdOficina" Parameter="idOficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdCategoria" Parameter="idCategoria" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUnidadMedida" Parameter="idUnidadMedida" Type="System.Int32" DbType="Int" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="Stock" Parameter="stock" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="GeneradoPor" Parameter="generadoPor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_SUMINISTRO_INVENTARIO_FINALResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(31,0)" CanBeNull="true" />
      <Column Name="IdSucursal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sucursal" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdUnidadMedida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnidadMedida" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Articulo" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StockMinimo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaIngreso0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="GeneradoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadRegistrosAgotadosAgotados" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_SUMINISTROS_INVENTARIO" Method="SP_PROCESAR_INFORMACION_SUMINISTROS_INVENTARIO">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(31,0)" />
    <Parameter Name="IdSucursal" Parameter="idSucursal" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdOficina" Parameter="idOficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdCategoria" Parameter="idCategoria" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUnidadMedida" Parameter="idUnidadMedida" Type="System.Int32" DbType="Int" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="Stock" Parameter="stock" Type="System.Int32" DbType="Int" />
    <Parameter Name="StockMinimo" Parameter="stockMinimo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_SUMINISTROS_INVENTARIOResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(31,0)" CanBeNull="true" />
      <Column Name="IdSucursal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdUnidadMedida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StockMinimo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaIngreso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_SUMINISTRO_SOLICITUDES" Method="SP_BUSCA_SUMINISTRO_SOLICITUDES">
    <Parameter Name="NumeroSolicitud" Parameter="numeroSolicitud" Type="System.Decimal" DbType="Decimal(31,0)" />
    <Parameter Name="IdSucursal" Parameter="idSucursal" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdOficina" Parameter="idOficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdDepartamento" Parameter="idDepartamento" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoArticulo" Parameter="codigoArticulo" Type="System.Int32" DbType="Int" />
    <Parameter Name="DescripcionArticulo" Parameter="descripcionArticulo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdCategoria" Parameter="idCategoria" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUnidadMedida" Parameter="idUnidadMedida" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IdEstatusSolicitud" Parameter="idEstatusSolicitud" Type="System.Int32" DbType="Int" />
    <Parameter Name="GeneradoPor" Parameter="generadoPor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_SUMINISTRO_SOLICITUDESResult">
      <Column Name="NumeroSolicitud" Type="System.Decimal" DbType="Decimal(31,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdSucursal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sucursal" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdDepartamento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Departamento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CodigoArticulo" Type="System.Decimal" DbType="Decimal(31,0)" CanBeNull="true" />
      <Column Name="DescripcionArticulo" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdUnidadMedida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnidadMedida" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="IdEstatusSolicitud" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GeneradoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CantidadSolicitudes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SolicitudesActivas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SolicitudesProcesadas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SolicitudesCanceladas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SolicitudesRechazadas" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_SUMINISTRO_SOLICITUDES" Method="SP_PROCESAR_INFORMACION_SUMINISTRO_SOLICITUDES">
    <Parameter Name="NumeroSolicitud" Parameter="numeroSolicitud" Type="System.Decimal" DbType="Decimal(31,0)" />
    <Parameter Name="IdSucursal" Parameter="idSucursal" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdOficina" Parameter="idOficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdDepartamento" Parameter="idDepartamento" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoArticulo" Parameter="codigoArticulo" Type="System.Decimal" DbType="Decimal(31,0)" />
    <Parameter Name="DescripcionArticulo" Parameter="descripcionArticulo" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="IdCategoria" Parameter="idCategoria" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUnidadMedida" Parameter="idUnidadMedida" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdEstatusSolicitud" Parameter="idEstatusSolicitud" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_SUMINISTRO_SOLICITUDESResult">
      <Column Name="NumeroSolicitud" Type="System.Decimal" DbType="Decimal(31,0)" CanBeNull="true" />
      <Column Name="IdSucursal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdDepartamento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoArticulo" Type="System.Decimal" DbType="Decimal(31,0)" CanBeNull="true" />
      <Column Name="DescripcionArticulo" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdUnidadMedida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdEstatusSolicitud" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_SUMINISTRO_SOLICITUDES" Method="SP_BUSCA_SUMINISTRO_SOLICITUDES1">
    <Parameter Name="NumeroSolicitud" Parameter="numeroSolicitud" Type="System.Decimal" DbType="Decimal(31,0)" />
    <Parameter Name="IdSucursal" Parameter="idSucursal" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdOficina" Parameter="idOficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdDepartamento" Parameter="idDepartamento" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoArticulo" Parameter="codigoArticulo" Type="System.Int32" DbType="Int" />
    <Parameter Name="DescripcionArticulo" Parameter="descripcionArticulo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdCategoria" Parameter="idCategoria" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUnidadMedida" Parameter="idUnidadMedida" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IdEstatusSolicitud" Parameter="idEstatusSolicitud" Type="System.Int32" DbType="Int" />
    <Parameter Name="GeneradoPor" Parameter="generadoPor" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_SUMINISTRO_SOLICITUDESResult1">
      <Column Name="NumeroSolicitud" Type="System.Decimal" DbType="Decimal(31,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdSucursal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sucursal" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdDepartamento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Departamento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CodigoArticulo" Type="System.Decimal" DbType="Decimal(31,0)" CanBeNull="true" />
      <Column Name="DescripcionArticulo" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdUnidadMedida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnidadMedida" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="IdEstatusSolicitud" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GeneradoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CantidadSolicitudes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SolicitudesActivas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SolicitudesProcesadas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SolicitudesCanceladas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SolicitudesRechazadas" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_SUMINISTRO_SOLICITUDES_ESPEJO" Method="SP_BUSCA_SUMINISTRO_SOLICITUDES_ESPEJO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Secuencial" Parameter="secuencial" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_SUMINISTRO_SOLICITUDES_ESPEJOResult">
      <Column Name="Secuencial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSucursal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sucursal" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdDepartamento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Departamento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CodigoArticulo" Type="System.Decimal" DbType="Decimal(31,0)" CanBeNull="true" />
      <Column Name="DescripcionArticulo" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdUnidadMedida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnidadMedida" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="IdEstatusSolicitud" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_SUMINISTRO_SOLICITUDES_ESPEJO" Method="SP_PROCESAR_INFORMACION_SUMINISTRO_SOLICITUDES_ESPEJO">
    <Parameter Name="Secuencial" Parameter="secuencial" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdSucursal" Parameter="idSucursal" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdOficina" Parameter="idOficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdDepartamento" Parameter="idDepartamento" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoArticulo" Parameter="codigoArticulo" Type="System.Decimal" DbType="Decimal(31,0)" />
    <Parameter Name="DescripcionArticulo" Parameter="descripcionArticulo" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="IdCategoria" Parameter="idCategoria" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUnidadMedida" Parameter="idUnidadMedida" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdEstatusSolicitud" Parameter="idEstatusSolicitud" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_SUMINISTRO_SOLICITUDES_ESPEJOResult">
      <Column Name="Secuencial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSucursal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdDepartamento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoArticulo" Type="System.Decimal" DbType="Decimal(31,0)" CanBeNull="true" />
      <Column Name="DescripcionArticulo" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdUnidadMedida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdEstatusSolicitud" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_SUMINISTRO_SOLICITUD_HEADER" Method="SP_PROCESAR_INFORMACION_SUMINISTRO_SOLICITUD_HEADER">
    <Parameter Name="NumeroSolicitud" Parameter="numeroSolicitud" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="EstatusSolicitud" Parameter="estatusSolicitud" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_SUMINISTRO_SOLICITUD_HEADERResult">
      <Column Name="NumeroSolicitud" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaSolicitud" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EstatusSolicitud" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_LISTADO_SOLICITUDES_HEADER" Method="SP_BUSCA_LISTADO_SOLICITUDES_HEADER">
    <Parameter Name="CodigoSucursal" Parameter="codigoSucursal" Type="System.Int32" DbType="Int" />
    <Parameter Name="CodigoOficina" Parameter="codigoOficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="CodigoDepartamento" Parameter="codigoDepartamento" Type="System.Int32" DbType="Int" />
    <Parameter Name="CodigoUsuario" Parameter="codigoUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroSocilitud" Parameter="numeroSocilitud" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="EstatusSolicitud" Parameter="estatusSolicitud" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_LISTADO_SOLICITUDES_HEADERResult">
      <Column Name="NumeroSolicitud" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroConector" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Persona" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IdSucursal" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Sucursal" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdOficina" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdDepartamento" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="Departamento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaSolicitud0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="EstatusSolicitud" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CantidadItems" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadSolicitudes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadSolicitudes_Activas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadSolicitudes_Procesadas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadSolicitudes_Canceladas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadSolicitudes_Rechazadas" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_SUMINISTRO_SOLICITUD_DETALLE" Method="SP_PROCESAR_INFORMACION_SUMINISTRO_SOLICITUD_DETALLE">
    <Parameter Name="SecuenciaDetalle" Parameter="secuenciaDetalle" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodigoArticulo" Parameter="codigoArticulo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="IdMedida" Parameter="idMedida" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdSucursal" Parameter="idSucursal" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdOficina" Parameter="idOficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdCategoria" Parameter="idCategoria" Type="System.Int32" DbType="Int" />
    <Parameter Name="StockMinimo" Parameter="stockMinimo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Despachado" Parameter="despachado" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_SUMINISTRO_SOLICITUD_DETALLEResult">
      <Column Name="SecuenciaDetalle" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoArticulo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdMedida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSucursal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StockMinimo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Despachado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_DETALLE_SOLICITUD" Method="SP_BUSCA_DETALLE_SOLICITUD">
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_BUSCA_DETALLE_SOLICITUDResult">
      <Column Name="SecuenciaDetalle" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroConector" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoArticulo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdMedida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnidadMedida" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSucursal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="StockMinimo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Disponible" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Despachado0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Despachado" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>