<?xml version="1.0" encoding="utf-8"?><Database Name="SysFlexSeguros" Class="BDConexionReportesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.25.24.3;Initial Catalog=SysFlexSeguros;User ID=sa" SettingsObjectName="UtilidadesAmigos.Data.Properties.Settings" SettingsPropertyName="SysFlexSegurosConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="Utililades.SP_GUARDAR_DATOS_REPORTE_POR_USUARIO_RESUMIDO" Method="SP_GUARDAR_DATOS_REPORTE_POR_USUARIO_RESUMIDO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Sucursal" Parameter="sucursal" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Oficina" Parameter="oficina" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Departaemnto" Parameter="departaemnto" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Total" Parameter="total" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="TipoMovimiento" Parameter="tipoMovimiento" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalRegistros" Parameter="totalRegistros" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TotalPrima" Parameter="totalPrima" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_DATOS_REPORTE_POR_USUARIO_RESUMIDOResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Sucursal" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Departaemnto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TipoMovimiento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalRegistros" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TotalPrima" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="FechaDesde" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaHasta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_GUARDAR_DATOS_PRODUCCION_USUARIO_DETALLE" Method="SP_GUARDAR_DATOS_PRODUCCION_USUARIO_DETALLE">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Sucursal" Parameter="sucursal" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Oficina" Parameter="oficina" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Departamento" Parameter="departamento" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Monto" Parameter="monto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="TotalRegistros" Parameter="totalRegistros" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TotalValor" Parameter="totalValor" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_DATOS_PRODUCCION_USUARIO_DETALLEResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaDesde" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaHasta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Sucursal" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Departamento" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalRegistros" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TotalValor" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCAR_PRODUCCION_ORIGEN" Method="SP_BUSCAR_PRODUCCION_ORIGEN">
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Tasa" Parameter="tasa" Type="System.Decimal" DbType="Decimal(20,2)" />
    <ElementType Name="SP_BUSCAR_PRODUCCION_ORIGENResult">
      <Column Name="CodRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ramo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroFacturaFormateado" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Asegurado" Type="System.String" DbType="VarChar(288) NOT NULL" CanBeNull="false" />
      <Column Name="Items" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(233) NOT NULL" CanBeNull="false" />
      <Column Name="CodIntermediario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CodSupervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(233) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaFormateada" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FechaInicioVigencia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaFinVigencia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="SumaAsegurada" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Ncf" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tipo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DescripcionTipo" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Bruto" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(21,2)" CanBeNull="true" />
      <Column Name="Neto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Tasa" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CodMoneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Moneda" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TasaUsada" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoPesos" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Mes" Type="System.String" DbType="VarChar(43) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalFacturado" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalFActuradoPesos" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalFActuradoDollar" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalFacturadoGeneral" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_DATOS_PRODUCCION" Method="SP_PROCESAR_INFORMACION_DATOS_PRODUCCION">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodRamo" Parameter="codRamo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroFacturaFormateado" Parameter="numeroFacturaFormateado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Asegurado" Parameter="asegurado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Items" Parameter="items" Type="System.Int32" DbType="Int" />
    <Parameter Name="Supervisor" Parameter="supervisor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodIntermediario" Parameter="codIntermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="CodSupervisor" Parameter="codSupervisor" Type="System.Int32" DbType="Int" />
    <Parameter Name="Intermediario" Parameter="intermediario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFormateada" Parameter="fechaFormateada" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="FechaInicioVigencia" Parameter="fechaInicioVigencia" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFinVigencia" Parameter="fechaFinVigencia" Type="System.DateTime" DbType="Date" />
    <Parameter Name="InicioVigencia" Parameter="inicioVigencia" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="FinVigencia" Parameter="finVigencia" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SumaAsegurada" Parameter="sumaAsegurada" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="CodOficina" Parameter="codOficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="Oficina" Parameter="oficina" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="Ncf" Parameter="ncf" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.Int32" DbType="Int" />
    <Parameter Name="DescripcionTipo" Parameter="descripcionTipo" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Bruto" Parameter="bruto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Impuesto" Parameter="impuesto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Neto" Parameter="neto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Tasa" Parameter="tasa" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Cobrado" Parameter="cobrado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="CodMoneda" Parameter="codMoneda" Type="System.Int32" DbType="Int" />
    <Parameter Name="Moneda" Parameter="moneda" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="TasaUsada" Parameter="tasaUsada" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoPesos" Parameter="montoPesos" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Mes" Parameter="mes" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_DATOS_PRODUCCIONResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ramo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroFacturaFormateado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Asegurado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Items" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodSupervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaFormateada" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FechaInicioVigencia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaFinVigencia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SumaAsegurada" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CodOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Ncf" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Tipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescripcionTipo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Bruto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Neto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Tasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CodMoneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Moneda" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TasaUsada" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoPesos" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Mes" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_DATOS_GRAFICOS" Method="SP_PROCESAR_INFORMACION_DATOS_GRAFICOS">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="EntidadRamo" Parameter="entidadRamo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ValorEnteroRamo" Parameter="valorEnteroRamo" Type="System.Int32" DbType="Int" />
    <Parameter Name="ValorDecimalRamo" Parameter="valorDecimalRamo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="EntidadAsegurado" Parameter="entidadAsegurado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ValorEnteroAsegurado" Parameter="valorEnteroAsegurado" Type="System.Int32" DbType="Int" />
    <Parameter Name="ValorDecimalAsegurado" Parameter="valorDecimalAsegurado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="EntidadSupervisor" Parameter="entidadSupervisor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ValorEnteroSupervisor" Parameter="valorEnteroSupervisor" Type="System.Int32" DbType="Int" />
    <Parameter Name="ValorDecimalSupervisor" Parameter="valorDecimalSupervisor" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="EntidadIntermediario" Parameter="entidadIntermediario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ValorEnteroIntermediario" Parameter="valorEnteroIntermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ValorDecimalIntermediario" Parameter="valorDecimalIntermediario" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="EntidadEstatus" Parameter="entidadEstatus" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ValorEnteroEstatus" Parameter="valorEnteroEstatus" Type="System.Int32" DbType="Int" />
    <Parameter Name="ValorDecimalEstatus" Parameter="valorDecimalEstatus" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="EntidadOficina" Parameter="entidadOficina" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ValorEnteroOficina" Parameter="valorEnteroOficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="ValorDecimalOficina" Parameter="valorDecimalOficina" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="EntidadConcepto" Parameter="entidadConcepto" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ValorEnteroConcepto" Parameter="valorEnteroConcepto" Type="System.Int32" DbType="Int" />
    <Parameter Name="ValorDecimalConcepto" Parameter="valorDecimalConcepto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="EntidadDescripcionTipo" Parameter="entidadDescripcionTipo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ValorEnteroDescripcionTipo" Parameter="valorEnteroDescripcionTipo" Type="System.Int32" DbType="Int" />
    <Parameter Name="ValorDecimalDescripcionTipo" Parameter="valorDecimalDescripcionTipo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="EntidadMoneda" Parameter="entidadMoneda" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ValorEnteroMoneda" Parameter="valorEnteroMoneda" Type="System.Int32" DbType="Int" />
    <Parameter Name="ValorDecimalMoneda" Parameter="valorDecimalMoneda" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_DATOS_GRAFICOSResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="EntidadRamo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorEnteroRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValorDecimalRamo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="EntidadAsegurado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorEnteroAsegurado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValorDecimalAsegurado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="EntidadSupervisor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorEnteroSupervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValorDecimalSupervisor" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="EntidadIntermediario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorEnteroIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValorDecimalIntermediario" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="EntidadEstatus" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorEnteroEstatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValorDecimalEstatus" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="EntidadOficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorEnteroOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValorDecimalOficina" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="EntidadConcepto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorEnteroConcepto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValorDecimalConcepto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="EntidadDescripcionTipo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorEnteroDescripcionTipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValorDecimalDescripcionTipo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="EntidadMoneda" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorEnteroMoneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValorDecimalMoneda" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_DATOS_PRODUCCION_NO_AGRUPADO_DETALLE" Method="SP_BUSCA_DATOS_PRODUCCION_NO_AGRUPADO_DETALLE">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="CodigoSupervisor" Parameter="codigoSupervisor" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="CodigoIntermediario" Parameter="codigoIntermediario" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Oficina" Parameter="oficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.Int32" DbType="Int" />
    <Parameter Name="CodMoneda" Parameter="codMoneda" Type="System.Int32" DbType="Int" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="Mes" Parameter="mes" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_BUSCA_DATOS_PRODUCCION_NO_AGRUPADO_DETALLEResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ramo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroFacturaFormateado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Asegurado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Items" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodSupervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaFormateada" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FechaInicioVigencia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaFinVigencia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SumaAsegurada" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CodOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Ncf" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Tipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescripcionTipo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Bruto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Neto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Tasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CodMoneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Moneda" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TasaUsada" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoPesos" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Mes" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CantidadRegistros" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalFacturado" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalFActuradoPesos" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalDollar" Type="System.Decimal" DbType="Decimal(38,4)" CanBeNull="true" />
      <Column Name="TotalFacturadoGeneral" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_DATO_POLIZA_PRODUCCION_REPORTE" Method="SP_BUSCA_DATO_POLIZA_PRODUCCION_REPORTE">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodRamo" Parameter="codRamo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroFacturaFormateado" Parameter="numeroFacturaFormateado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Asegurado" Parameter="asegurado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Items" Parameter="items" Type="System.Int32" DbType="Int" />
    <Parameter Name="Supervisor" Parameter="supervisor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodIntermediario" Parameter="codIntermediario" Type="System.Int32" DbType="Int" />
    <Parameter Name="CodSupervisor" Parameter="codSupervisor" Type="System.Int32" DbType="Int" />
    <Parameter Name="Intermediario" Parameter="intermediario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFormateada" Parameter="fechaFormateada" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="FechaInicioVigencia" Parameter="fechaInicioVigencia" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFinVigencia" Parameter="fechaFinVigencia" Type="System.DateTime" DbType="Date" />
    <Parameter Name="InicioVigencia" Parameter="inicioVigencia" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="FinVigencia" Parameter="finVigencia" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SumaAsegurada" Parameter="sumaAsegurada" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="CodOficina" Parameter="codOficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="Oficina" Parameter="oficina" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="Ncf" Parameter="ncf" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.Int32" DbType="Int" />
    <Parameter Name="DescripcionTipo" Parameter="descripcionTipo" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Bruto" Parameter="bruto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Impuesto" Parameter="impuesto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Neto" Parameter="neto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Tasa" Parameter="tasa" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Cobrado" Parameter="cobrado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="CodMoneda" Parameter="codMoneda" Type="System.Int32" DbType="Int" />
    <Parameter Name="Moneda" Parameter="moneda" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="TasaUsada" Parameter="tasaUsada" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoPesos" Parameter="montoPesos" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Mes" Parameter="mes" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_BUSCA_DATO_POLIZA_PRODUCCION_REPORTEResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ramo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroFacturaFormateado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Asegurado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Items" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodSupervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaFormateada" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FechaInicioVigencia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaFinVigencia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SumaAsegurada" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CodOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Ncf" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Tipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescripcionTipo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Bruto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Neto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Tasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CodMoneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Moneda" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TasaUsada" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoPesos" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Mes" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_DATOS_PRODUCCION_NO_AGRUPADO_RESUMEN" Method="SP_BUSCA_DATOS_PRODUCCION_NO_AGRUPADO_RESUMEN">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="CodigoSupervisor" Parameter="codigoSupervisor" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="CodigoIntermediario" Parameter="codigoIntermediario" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Oficina" Parameter="oficina" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.Int32" DbType="Int" />
    <Parameter Name="CodMoneda" Parameter="codMoneda" Type="System.Int32" DbType="Int" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="Mes" Parameter="mes" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_BUSCA_DATOS_PRODUCCION_NO_AGRUPADO_RESUMENResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ramo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodIntermediario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodSupervisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodOficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Tipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescripcionTipo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Bruto" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Neto" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Cobrado" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="CodMoneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Moneda" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TasaUsada" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoPesos" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_DATOS_REPORTE_INTERMEDIARIO_INTERNO" Method="SP_PROCESAR_DATOS_REPORTE_INTERMEDIARIO_INTERNO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Oficina" Parameter="oficina" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Intermediario" Parameter="intermediario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="PorcientoComision" Parameter="porcientoComision" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="RNC" Parameter="rNC" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Cuenta" Parameter="cuenta" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Banco" Parameter="banco" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="Bruto" Parameter="bruto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Neto" Parameter="neto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Comision" Parameter="comision" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Retencion" Parameter="retencion" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Avance" Parameter="avance" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="APagar" Parameter="aPagar" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_DATOS_REPORTE_INTERMEDIARIO_INTERNOResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Ramo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Oficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PorcientoComision" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cuenta" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Banco" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Bruto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Neto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Comision" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Retencion" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Avance" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="APagar" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="FechaDesde" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaHasta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>