<?xml version="1.0" encoding="utf-8"?><Database Name="SysFlexSeguros" Class="BDOpcionesAdministradorDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.26.24.199;Initial Catalog=SysFlexSeguros;Integrated Security=False;User ID=sa" SettingsObjectName="UtilidadesAmigos.Data.Properties.Settings" SettingsPropertyName="SysFlexSegurosConnectionString16" Provider="System.Data.SqlClient" />
  <Function Name="Utililades.SP_BUSCA_RUTA_ARCHIVO_BAKUP" Method="SP_BUSCA_RUTA_ARCHIVO_BAKUP">
    <Parameter Name="IdRutaArchivoBakup" Parameter="idRutaArchivoBakup" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_RUTA_ARCHIVO_BAKUPResult">
      <Column Name="IdRutaArchivoBakup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RutaBackup" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="ExtencionBackup" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MANTENIMIENTO_RUTA_ARCHIVO_BACKUP" Method="SP_MANTENIMIENTO_RUTA_ARCHIVO_BACKUP">
    <Parameter Name="IdRutaArchivoBakup" Parameter="idRutaArchivoBakup" Type="System.Int32" DbType="Int" />
    <Parameter Name="RutaBackup" Parameter="rutaBackup" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="ExtencionBackup" Parameter="extencionBackup" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_RUTA_ARCHIVO_BACKUPResult">
      <Column Name="IdRutaArchivoBakup" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RutaBackup" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="ExtencionBackup" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_GENERARBAKUP_DATABASE" Method="SP_GENERARBAKUP_DATABASE">
    <Parameter Name="RutaBaseDatos" Parameter="rutaBaseDatos" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GENERARBAKUP_DATABASEResult">
      <Column Name="RutaArchivo" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MANTENIMIENTO_HISTORIAL_BACKUP_DATABASE" Method="SP_MANTENIMIENTO_HISTORIAL_BACKUP_DATABASE">
    <Parameter Name="IdHistorialBakupDatabase" Parameter="idHistorialBakupDatabase" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroBackup" Parameter="numeroBackup" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NombreArchivo" Parameter="nombreArchivo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Hora" Parameter="hora" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IdEstatus" Parameter="idEstatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_HISTORIAL_BACKUP_DATABASEResult">
      <Column Name="IdHistorialBakupDatabase" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroBackup" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NombreArchivo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Hora" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdEstatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_CORREOS_ENVIAR" Method="SP_BUSCA_CORREOS_ENVIAR">
    <Parameter Name="IdCorreoEnviar" Parameter="idCorreoEnviar" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdProceso" Parameter="idProceso" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="SP_BUSCA_CORREOS_ENVIARResult">
      <Column Name="IdCorreoEnviar" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdProceso" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ProcesoCorreo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_MANTENIMIENTO_CORREOS_ENVIAR" Method="SP_MANTENIMIENTO_CORREOS_ENVIAR">
    <Parameter Name="IdCorreoEnviar" Parameter="idCorreoEnviar" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdProceso" Parameter="idProceso" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_CORREOS_ENVIARResult">
      <Column Name="IdCorreoEnviar" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdProceso" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_HISTORIAL_BAKUP_DATABASE" Method="SP_BUSCA_HISTORIAL_BAKUP_DATABASE">
    <Parameter Name="IdHistorialBakup" Parameter="idHistorialBakup" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroBackup" Parameter="numeroBackup" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Fechadesde" Parameter="fechadesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IdEstatus" Parameter="idEstatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NombreUsuario" Parameter="nombreUsuario" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_BUSCA_HISTORIAL_BAKUP_DATABASEResult">
      <Column Name="IdHistorialBakupDatabase" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroBackup" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="NombreArchivo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Hora0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="IdEstatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>