<?xml version="1.0" encoding="utf-8"?><Database Name="SysFlexSeguros" Class="BDSuperIntendenciaConexionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.25.24.3;Initial Catalog=SysFlexSeguros;Integrated Security=False;User ID=sa" SettingsObjectName="UtilidadesAmigos.Data.Properties.Settings" SettingsPropertyName="SysFlexSegurosConnectionString2" Provider="System.Data.SqlClient" />
  <Function Name="Utililades.SP_BUSCA_REGISTROS_SUPER_INTENDENCIA_CLIENTE" Method="SP_BUSCA_REGISTROS_SUPER_INTENDENCIA_CLIENTE">
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Chasis" Parameter="chasis" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Placa" Parameter="placa" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Cotizacion" Parameter="cotizacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="ReportePresico" Parameter="reportePresico" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_REGISTROS_SUPER_INTENDENCIA_CLIENTEResult">
      <Column Name="Nombre" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmpresaLabora" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="RNCEmpresaLabora" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="NombreVendedor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="RNCIntermediario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LicenciaSeguro" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ramo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TipoVehiculo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Modelo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Ano" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Placa" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Chasis" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="MontoAsegurado" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodRamo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Prima" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="FechaInicioVigencia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FechaFinVigencia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_REGISTROS_SUPER_INTENDENCIA_INTERMEDIARIO" Method="SP_BUSCA_REGISTROS_SUPER_INTENDENCIA_INTERMEDIARIO">
    <Parameter Name="Codigo" Parameter="codigo" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_BUSCA_REGISTROS_SUPER_INTENDENCIA_INTERMEDIARIOResult">
      <Column Name="Codigo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estatus0" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="TipoRnc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Rnc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Fecha_Entrada" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaEntrada" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Fec_Nac" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TelefonoOficina" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="LicenciaSeguro" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Oficina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreOficina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CtaBanco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Banco" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_REGISTRO_SUPER_INTENDENCIA_PROVEEDOR" Method="SP_BUSCA_REGISTRO_SUPER_INTENDENCIA_PROVEEDOR">
    <Parameter Name="Codigo" Parameter="codigo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SP_BUSCA_REGISTRO_SUPER_INTENDENCIA_PROVEEDORResult">
      <Column Name="Codigo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TipoCliente0" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoCliente" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TipoRnc" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Rnc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NombreCliente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreado" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="TelefonoCasa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TelefonoOficina" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CuentaBanco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Banco" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreBanco" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TipoCuentaBanco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClaseProveedor" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="FechaUltPago0" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaUltPago" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="LimiteCredito" Type="System.Decimal" DbType="Decimal(19,2)" CanBeNull="true" />
      <Column Name="ToTalPagado" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CantidadSolicitud" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadSolicitudCanceladas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UltimaFechaSolicitud" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="NoSolicitud" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescripcionTipoSolicitud" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Valor" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NumeroCheque" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaCheque" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Concepto1" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Concepto2" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_REGISTROS_SUPER_INTENDENCIA_ASEGURADOS" Method="SP_BUSCA_REGISTROS_SUPER_INTENDENCIA_ASEGURADOS">
    <Parameter Name="NombreAsegurado" Parameter="nombreAsegurado" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Cotizacion" Parameter="cotizacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_REGISTROS_SUPER_INTENDENCIA_ASEGURADOSResult">
      <Column Name="Nombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Item" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Intermediario" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Licencia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RNCIntermediario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Prima" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="InicioVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="TipoVehiculo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Modelo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Chasis" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Placa" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Ano" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="MontoAsegurado" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_REGISTROS_SUPER_INTENDENCIA_ASEGURADO_GENERAL" Method="SP_BUSCA_REGISTROS_SUPER_INTENDENCIA_ASEGURADO_GENERAL">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroRNC" Parameter="numeroRNC" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Cotizacion" Parameter="cotizacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdAsegurado" Parameter="idAsegurado" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_REGISTROS_SUPER_INTENDENCIA_ASEGURADO_GENERALResult">
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdAsegurado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Parentezco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Sexo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_REGISTROS_SUPER_INTENDENCIA_DEPENDIENTE" Method="SP_BUSCA_REGISTROS_SUPER_INTENDENCIA_DEPENDIENTE">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroRNC" Parameter="numeroRNC" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Cotizacion" Parameter="cotizacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdAsegurado" Parameter="idAsegurado" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_REGISTROS_SUPER_INTENDENCIA_DEPENDIENTEResult">
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cotizacion" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Secuencia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdAsegurado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Parentezco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Sexo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_INFORMACION_PERSONAS_ARCHIVO_SUPER_INTENDENCIA" Method="SP_PROCESAR_INFORMACION_PERSONAS_ARCHIVO_SUPER_INTENDENCIA">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_INFORMACION_PERSONAS_ARCHIVO_SUPER_INTENDENCIAResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_PROCESAR_DATA_RESULTADO_BUSQUEDA_PERSONA_SUPER_INTENDENCIA" Method="SP_PROCESAR_DATA_RESULTADO_BUSQUEDA_PERSONA_SUPER_INTENDENCIA">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Poliza" Parameter="poliza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Reclamacion" Parameter="reclamacion" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Ramo" Parameter="ramo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MontoAsegurado" Parameter="montoAsegurado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Prima" Parameter="prima" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="InicioVigencia" Parameter="inicioVigencia" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FinVigencia" Parameter="finVigencia" Type="System.DateTime" DbType="Date" />
    <Parameter Name="TipoBusqueda" Parameter="tipoBusqueda" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="EncontradoComo" Parameter="encontradoComo" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_PROCESAR_DATA_RESULTADO_BUSQUEDA_PERSONA_SUPER_INTENDENCIAResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Poliza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Reclamacion" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ramo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MontoAsegurado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Prima" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="InicioVigencia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FinVigencia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TipoBusqueda" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EncontradoComo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Utililades.SP_BUSCA_INFORMACION_PERSONAS_REGISTRADAS_ARCHIVO" Method="SP_BUSCA_INFORMACION_PERSONAS_REGISTRADAS_ARCHIVO">
    <Parameter Name="IdUSuario" Parameter="idUSuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(30)" />
    <ElementType Name="SP_BUSCA_INFORMACION_PERSONAS_REGISTRADAS_ARCHIVOResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>